using System.Collections.Immutable;

namespace Strategos.Ontology.Provenance;

/// <summary>
/// Builds the W3C PROV-DM core provenance for a reified association (DR-16, T23,
/// #126), sourcing the asserting agent from the G1 <c>CurrentAgentIdentity</c>
/// seam.
/// </summary>
/// <remarks>
/// INV-2 (self-contained): the seam is a <see cref="Func{TResult}"/> returning the
/// current agent's opaque header-safe value, so the core ontology takes NO
/// dependency on the identity package — the caller binds
/// <c>() =&gt; accessor.CurrentAgent?.Value</c> at the composition seam. When the
/// seam returns <c>null</c> (no envelope / no agent context), provenance is NOT
/// attributed to a fabricated agent: the <see cref="ProvRelation.WasAttributedTo"/>
/// / <see cref="ProvRelation.WasAssociatedWith"/> influences are simply omitted.
/// INV-6 (sealed): the recorder is a sealed class.
/// </remarks>
public sealed class AssociationProvenanceRecorder
{
    private readonly Func<string?> currentAgent;

    /// <summary>
    /// Initializes a new instance of the <see cref="AssociationProvenanceRecorder"/>
    /// class.
    /// </summary>
    /// <param name="currentAgent">
    /// The <c>CurrentAgentIdentity</c> seam: returns the current agent's opaque
    /// header-safe value (e.g. <c>accessor.CurrentAgent?.Value</c>), or
    /// <c>null</c> when no agent context is active.
    /// </param>
    public AssociationProvenanceRecorder(Func<string?> currentAgent)
    {
        ArgumentNullException.ThrowIfNull(currentAgent);
        this.currentAgent = currentAgent;
    }

    /// <summary>
    /// Attaches PROV-DM core provenance to a reified association: the association
    /// (Entity) <c>wasGeneratedBy</c> the activity, and — when the
    /// <c>CurrentAgentIdentity</c> seam yields an agent — <c>wasAttributedTo</c>
    /// that agent and the activity <c>wasAssociatedWith</c> it.
    /// </summary>
    /// <param name="associationId">The reified association's business id (the Entity).</param>
    /// <param name="activityId">The id of the activity that generated the assertion.</param>
    /// <param name="reason">The human-readable reason for the assertion.</param>
    public AssociationProvenance Attach(string associationId, string activityId, string reason)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(associationId);
        ArgumentException.ThrowIfNullOrWhiteSpace(activityId);
        ArgumentException.ThrowIfNullOrWhiteSpace(reason);

        var entity = new ProvEntity(associationId);
        var activity = new ProvActivity(activityId);
        var agentValue = this.currentAgent();
        var agent = agentValue is null ? null : new ProvAgent(agentValue);

        // The entity was always generated by the activity (no agent required).
        var influences = new List<ProvInfluence>
        {
            new(entity.Id, ProvRelation.WasGeneratedBy, activity.Id),
        };

        // Agent-bearing relations only when the seam yielded an agent — never
        // fabricate attribution.
        if (agent is not null)
        {
            influences.Add(new ProvInfluence(entity.Id, ProvRelation.WasAttributedTo, agent.Id));
            influences.Add(new ProvInfluence(activity.Id, ProvRelation.WasAssociatedWith, agent.Id));
        }

        return new AssociationProvenance
        {
            Entity = entity,
            Activity = activity,
            Agent = agent,
            Reason = reason,
            Influences = influences.ToImmutableArray(),
        };
    }
}
