namespace Strategos.Ontology.Provenance;

/// <summary>
/// The seven W3C PROV-DM <b>core</b> relations (DR-16, T23, #126). This is the
/// CORE subset only — Bundles and Collections are deliberately out of scope, so a
/// new value here should be a genuine PROV-DM core relation, never a bundle/
/// collection construct.
/// </summary>
/// <remarks>
/// Mapped from the PROV-DM core: see <c>https://www.w3.org/TR/prov-dm/</c>. The
/// reified association is the qualified-influence node; provenance attaches to the
/// reifier, not the endpoint type (orthogonal to the P1/P2 storage shape).
/// </remarks>
public enum ProvRelation
{
    /// <summary>Entity → Activity: the entity was generated by the activity.</summary>
    WasGeneratedBy,

    /// <summary>Activity → Entity: the activity used the entity.</summary>
    Used,

    /// <summary>Activity → Activity: one activity was informed by another.</summary>
    WasInformedBy,

    /// <summary>Entity → Entity: one entity was derived from another.</summary>
    WasDerivedFrom,

    /// <summary>Entity → Agent: the entity was attributed to the agent.</summary>
    WasAttributedTo,

    /// <summary>Activity → Agent: the activity was associated with the agent.</summary>
    WasAssociatedWith,

    /// <summary>Agent → Agent: one agent acted on behalf of another.</summary>
    ActedOnBehalfOf,
}
