// -----------------------------------------------------------------------
// <copyright file="FileHeaderHelperTests.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System.Text;

using Strategos.Generators.Helpers;

namespace Strategos.Generators.Tests.Helpers;

/// <summary>
/// Unit tests for the <see cref="FileHeaderHelper"/> class.
/// </summary>
[Property("Category", "Unit")]
public class FileHeaderHelperTests
{
    // =============================================================================
    // A. AppendAutoGeneratedHeader Tests
    // =============================================================================

    /// <summary>
    /// Verifies that AppendAutoGeneratedHeader adds the auto-generated comment.
    /// </summary>
    [Test]
    public async Task AppendAutoGeneratedHeader_AppendsAutoGeneratedComment()
    {
        // Arrange
        var sb = new StringBuilder();

        // Act
        FileHeaderHelper.AppendAutoGeneratedHeader(sb);

        // Assert
        await Assert.That(sb.ToString()).Contains("// <auto-generated/>");
    }

    /// <summary>
    /// Verifies that AppendAutoGeneratedHeader adds nullable enable directive.
    /// </summary>
    [Test]
    public async Task AppendAutoGeneratedHeader_AppendsNullableEnable()
    {
        // Arrange
        var sb = new StringBuilder();

        // Act
        FileHeaderHelper.AppendAutoGeneratedHeader(sb);

        // Assert
        await Assert.That(sb.ToString()).Contains("#nullable enable");
    }

    /// <summary>
    /// Verifies that AppendAutoGeneratedHeader ends with a blank line.
    /// </summary>
    [Test]
    public async Task AppendAutoGeneratedHeader_EndsWithBlankLine()
    {
        // Arrange
        var sb = new StringBuilder();

        // Act
        FileHeaderHelper.AppendAutoGeneratedHeader(sb);
        var result = sb.ToString();

        // Assert - Should end with two newlines (the blank line after #nullable enable)
        await Assert.That(result).EndsWith(Environment.NewLine + Environment.NewLine);
    }

    // =============================================================================
    // B. AppendNamespace Tests
    // =============================================================================

    /// <summary>
    /// Verifies that AppendNamespace emits file-scoped namespace.
    /// </summary>
    [Test]
    public async Task AppendNamespace_EmitsFileScopedNamespace()
    {
        // Arrange
        var sb = new StringBuilder();

        // Act
        FileHeaderHelper.AppendNamespace(sb, "MyNamespace");

        // Assert
        await Assert.That(sb.ToString()).Contains("namespace MyNamespace;");
    }

    /// <summary>
    /// Verifies that AppendNamespace ends with a blank line.
    /// </summary>
    [Test]
    public async Task AppendNamespace_EndsWithBlankLine()
    {
        // Arrange
        var sb = new StringBuilder();

        // Act
        FileHeaderHelper.AppendNamespace(sb, "MyNamespace");
        var result = sb.ToString();

        // Assert
        await Assert.That(result).EndsWith(Environment.NewLine + Environment.NewLine);
    }

    // =============================================================================
    // C. AppendUsings Tests
    // =============================================================================

    /// <summary>
    /// Verifies that AppendUsings emits using directives.
    /// </summary>
    [Test]
    public async Task AppendUsings_EmitsUsingDirectives()
    {
        // Arrange
        var sb = new StringBuilder();

        // Act
        FileHeaderHelper.AppendUsings(sb, "System", "System.Collections.Generic");

        // Assert
        var result = sb.ToString();
        await Assert.That(result).Contains("using System;");
        await Assert.That(result).Contains("using System.Collections.Generic;");
    }

    /// <summary>
    /// Verifies that AppendUsings with empty array produces only a blank line.
    /// </summary>
    [Test]
    public async Task AppendUsings_WithNoNamespaces_ProducesBlankLine()
    {
        // Arrange
        var sb = new StringBuilder();

        // Act
        FileHeaderHelper.AppendUsings(sb);

        // Assert - Should just have the trailing blank line
        await Assert.That(sb.ToString()).IsEqualTo(Environment.NewLine);
    }

    /// <summary>
    /// Verifies that AppendUsings ends with a blank line.
    /// </summary>
    [Test]
    public async Task AppendUsings_EndsWithBlankLine()
    {
        // Arrange
        var sb = new StringBuilder();

        // Act
        FileHeaderHelper.AppendUsings(sb, "System");
        var result = sb.ToString();

        // Assert
        await Assert.That(result).EndsWith(Environment.NewLine + Environment.NewLine);
    }

    // =============================================================================
    // D. Guard Clause Tests
    // =============================================================================

    /// <summary>
    /// Verifies that AppendAutoGeneratedHeader throws when StringBuilder is null.
    /// </summary>
    [Test]
    public async Task AppendAutoGeneratedHeader_NullStringBuilder_ThrowsArgumentNullException()
    {
        await Assert.That(() => FileHeaderHelper.AppendAutoGeneratedHeader(null!))
            .Throws<ArgumentNullException>();
    }

    /// <summary>
    /// Verifies that AppendNamespace throws when StringBuilder is null.
    /// </summary>
    [Test]
    public async Task AppendNamespace_NullStringBuilder_ThrowsArgumentNullException()
    {
        await Assert.That(() => FileHeaderHelper.AppendNamespace(null!, "MyNamespace"))
            .Throws<ArgumentNullException>();
    }

    /// <summary>
    /// Verifies that AppendNamespace throws when namespace is null.
    /// </summary>
    [Test]
    public async Task AppendNamespace_NullNamespace_ThrowsArgumentNullException()
    {
        var sb = new StringBuilder();
        await Assert.That(() => FileHeaderHelper.AppendNamespace(sb, null!))
            .Throws<ArgumentNullException>();
    }

    /// <summary>
    /// Verifies that AppendUsings throws when StringBuilder is null.
    /// </summary>
    [Test]
    public async Task AppendUsings_NullStringBuilder_ThrowsArgumentNullException()
    {
        await Assert.That(() => FileHeaderHelper.AppendUsings(null!, "System"))
            .Throws<ArgumentNullException>();
    }

    /// <summary>
    /// Verifies that AppendUsings throws when namespaces array is null.
    /// </summary>
    [Test]
    public async Task AppendUsings_NullNamespaces_ThrowsArgumentNullException()
    {
        var sb = new StringBuilder();
        await Assert.That(() => FileHeaderHelper.AppendUsings(sb, null!))
            .Throws<ArgumentNullException>();
    }
}
