// =============================================================================
// <copyright file="OntologyContractEmitter.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// =============================================================================

using System.Text;
using System.Text.Json;

namespace Strategos.Contracts.Codegen;

/// <summary>
/// RecordEmitter extension for contract-authored ontology operations. TypeSpec
/// decorators are persisted as <c>x-strategos-*</c> JSON Schema metadata; this
/// extension projects that provider-neutral metadata into immutable ontology
/// descriptors without introducing an Ontology dependency into Contracts.
/// </summary>
internal sealed class OntologyContractEmitter(string outputDir) : ISchemaEmissionExtension
{
    private const string OutputFileName = "ContractOntology.g.cs";

    public async Task<int> EmitAsync(string schemasDir)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(schemasDir);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputDir);

        var actions = new List<ContractAction>();
        foreach (var schemaFile in Directory.GetFiles(schemasDir, "*.json")
                     .OrderBy(path => path, StringComparer.Ordinal))
        {
            using var parsed = JsonDocument.Parse(
                await File.ReadAllTextAsync(schemaFile).ConfigureAwait(false));
            if (ContractAction.TryRead(parsed.RootElement, out var action))
            {
                actions.Add(action!);
            }
        }

        Directory.CreateDirectory(outputDir);
        await File.WriteAllTextAsync(
            Path.Combine(outputDir, OutputFileName),
            Emit(actions),
            Encoding.UTF8).ConfigureAwait(false);
        return 0;
    }

    private static string Emit(IReadOnlyList<ContractAction> actions)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System.Collections.Immutable;");
        sb.AppendLine("using Strategos.Ontology.Descriptors;");
        sb.AppendLine();
        sb.AppendLine("namespace Strategos.Ontology.Contracts;");
        sb.AppendLine();
        sb.AppendLine("internal static class GeneratedContractOntology");
        sb.AppendLine("{");
        sb.AppendLine("    internal static ImmutableArray<ObjectTypeDescriptor> ObjectTypes { get; } =");
        sb.AppendLine("    [");

        foreach (var objectGroup in actions
                     .GroupBy(action => (action.DomainName, action.ObjectName, action.ObjectKind))
                     .OrderBy(group => group.Key.DomainName, StringComparer.Ordinal)
                     .ThenBy(group => group.Key.ObjectName, StringComparer.Ordinal))
        {
            sb.AppendLine("        new ObjectTypeDescriptor");
            sb.AppendLine("        {");
            sb.Append("            Name = ").Append(Literal(objectGroup.Key.ObjectName)).AppendLine(",");
            sb.Append("            DomainName = ").Append(Literal(objectGroup.Key.DomainName)).AppendLine(",");
            sb.Append("            SymbolKey = ").Append(Literal(
                $"typespec://{objectGroup.Key.DomainName}/{objectGroup.Key.ObjectName}")).AppendLine(",");
            sb.AppendLine("            LanguageId = \"typespec\",");
            sb.AppendLine("            Source = DescriptorSource.HandAuthoredContract,");
            sb.Append("            Kind = ObjectKind.").Append(MapObjectKind(objectGroup.Key.ObjectKind)).AppendLine(",");
            sb.AppendLine("            Actions =");
            sb.AppendLine("            [");

            foreach (var action in objectGroup.OrderBy(action => action.ActionName, StringComparer.Ordinal))
            {
                EmitAction(sb, action);
            }

            sb.AppendLine("            ],");
            sb.AppendLine("        },");
        }

        sb.AppendLine("    ];");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitAction(StringBuilder sb, ContractAction action)
    {
        sb.Append("                new ActionDescriptor(")
            .Append(Literal(action.ActionName)).Append(", ")
            .Append(Literal(action.Description)).AppendLine(")");
        sb.AppendLine("                {");
        sb.Append("                    IsReadOnly = ").Append(Boolean(action.IsReadOnly)).AppendLine(",");
        sb.Append("                    Idempotent = ").Append(Boolean(action.Idempotent)).AppendLine(",");
        sb.Append("                    RequiredAuthority = ").Append(NullableLiteral(action.Authority)).AppendLine(",");
        sb.Append("                    RequiresConfirmation = ").Append(Boolean(action.RequiresConfirmation)).AppendLine(",");
        sb.Append("                    AllowedClients = ").Append(StringArray(action.Clients)).AppendLine(",");

        if (action.RelationName is not null)
        {
            sb.AppendLine("                    Preconditions =");
            sb.AppendLine("                    [");
            sb.AppendLine("                        new ActionPrecondition");
            sb.AppendLine("                        {");
            sb.Append("                            Expression = ").Append(Literal(
                $"relation:{action.RelationName}")).AppendLine(",");
            sb.Append("                            Description = ").Append(Literal(
                $"Requires relation '{action.RelationName}'.")).AppendLine(",");
            sb.AppendLine("                            Kind = PreconditionKind.RelationHolds,");
            sb.Append("                            RelationName = ").Append(Literal(action.RelationName)).AppendLine(",");
            sb.Append("                            LinkPath = ").Append(StringArray(action.LinkPath)).AppendLine(",");
            sb.AppendLine("                        },");
            sb.AppendLine("                    ],");
        }

        sb.AppendLine("                },");
    }

    private static string MapObjectKind(string kind) => kind.ToLowerInvariant() switch
    {
        "entity" => "Entity",
        "process" => "Process",
        "association" => "Association",
        _ => throw new InvalidOperationException($"Unknown contract ontology object kind '{kind}'."),
    };

    private static string StringArray(IReadOnlyList<string> values) => values.Count == 0
        ? "ImmutableArray<string>.Empty"
        : $"ImmutableArray.Create({string.Join(", ", values.Select(Literal))})";

    private static string NullableLiteral(string? value) => value is null ? "null" : Literal(value);

    private static string Literal(string value) => JsonSerializer.Serialize(value);

    private static string Boolean(bool value) => value ? "true" : "false";

    private sealed record ContractAction(
        string DomainName,
        string ObjectName,
        string ObjectKind,
        string ActionName,
        string Description,
        string? Authority,
        string? RelationName,
        IReadOnlyList<string> LinkPath,
        IReadOnlyList<string> Clients,
        bool RequiresConfirmation,
        bool IsReadOnly,
        bool Idempotent)
    {
        public static bool TryRead(JsonElement root, out ContractAction? action)
        {
            action = null;
            if (!TryString(root, "x-strategos-action-name", out var actionName))
            {
                return false;
            }

            if (!TryString(root, "x-strategos-domain", out var domainName)
                || !TryString(root, "x-strategos-object", out var objectName)
                || !TryString(root, "x-strategos-object-kind", out var objectKind))
            {
                throw new InvalidOperationException(
                    $"Contract ontology action '{actionName}' is missing objectKind metadata.");
            }

            action = new ContractAction(
                domainName!,
                objectName!,
                objectKind!,
                actionName!,
                ReadString(root, "x-strategos-action-description") ?? actionName!,
                ReadString(root, "x-strategos-authority"),
                ReadString(root, "x-strategos-relation"),
                ReadStrings(root, "x-strategos-link-path"),
                ReadStrings(root, "x-strategos-clients"),
                ReadBoolean(root, "x-strategos-confirm"),
                ReadBoolean(root, "x-strategos-read-only"),
                ReadBoolean(root, "x-strategos-idempotent"));
            return true;
        }

        private static bool TryString(JsonElement root, string propertyName, out string? value)
        {
            value = ReadString(root, propertyName);
            return value is not null;
        }

        private static string? ReadString(JsonElement root, string propertyName) =>
            root.TryGetProperty(propertyName, out var value) && value.ValueKind == JsonValueKind.String
                ? value.GetString()
                : null;

        private static bool ReadBoolean(JsonElement root, string propertyName) =>
            root.TryGetProperty(propertyName, out var value)
            && value.ValueKind is JsonValueKind.True or JsonValueKind.False
            && value.GetBoolean();

        private static IReadOnlyList<string> ReadStrings(JsonElement root, string propertyName) =>
            root.TryGetProperty(propertyName, out var value) && value.ValueKind == JsonValueKind.Array
                ? value.EnumerateArray()
                    .Where(item => item.ValueKind == JsonValueKind.String)
                    .Select(item => item.GetString()!)
                    .ToArray()
                : [];
    }
}
