// =============================================================================
// <copyright file="RecordEmitter.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// =============================================================================

using System.Globalization;
using System.Text;
using NJsonSchema;

namespace Strategos.Contracts.Codegen;

/// <summary>
/// Emits one C# <c>sealed record</c> per JSON Schema document, in the shape
/// mandated by INV-6 (sealed record) and INV-7 (<c>{ get; init; }</c> +
/// <see cref="IReadOnlyList{T}"/> collections). NJsonSchema parses and resolves
/// (<c>$ref</c>) the schema; this template owns the emitted shape.
/// </summary>
public static class RecordEmitter
{
    private const string Namespace = "Strategos.Contracts.Generated";

    /// <summary>Generates records for every <c>*.json</c> schema in <paramref name="schemasDir"/>.</summary>
    /// <param name="schemasDir">Directory containing emitted JSON Schema documents.</param>
    /// <param name="outputDir">Directory the <c>*.g.cs</c> records are written to.</param>
    /// <returns>Process exit code (0 on success).</returns>
    public static async Task<int> RunAsync(string schemasDir, string outputDir)
    {
        if (!Directory.Exists(schemasDir))
        {
            await Console.Error.WriteLineAsync($"schemas dir not found: {schemasDir}").ConfigureAwait(false);
            return 1;
        }

        Directory.CreateDirectory(outputDir);

        // Clean stale generated files so deletions in TypeSpec propagate.
        foreach (var stale in Directory.GetFiles(outputDir, "*.g.cs"))
        {
            File.Delete(stale);
        }

        var schemaFiles = Directory.GetFiles(schemasDir, "*.json").OrderBy(f => f, StringComparer.Ordinal);
        foreach (var schemaFile in schemaFiles)
        {
            var schema = await JsonSchema.FromFileAsync(schemaFile).ConfigureAwait(false);
            if (!schema.Type.HasFlag(JsonObjectType.Object) || schema.ActualProperties.Count == 0)
            {
                // Enums / scalar aliases are not records; skip for Phase 0.
                continue;
            }

            var recordName = ToPascalCase(Path.GetFileNameWithoutExtension(schemaFile));
            var source = EmitRecord(recordName, schema);
            await File.WriteAllTextAsync(Path.Combine(outputDir, recordName + ".g.cs"), source).ConfigureAwait(false);
        }

        return 0;
    }

    private static string EmitRecord(string recordName, JsonSchema schema)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// =============================================================================");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     Generated by Strategos.Contracts.Codegen from TypeSpec-emitted JSON Schema.");
        sb.AppendLine("//     DO NOT EDIT — hand-edits are rejected by the codegen-guard CI workflow.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// =============================================================================");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.Append("namespace ").Append(Namespace).AppendLine(";");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(schema.Description))
        {
            AppendXmlDoc(sb, schema.Description, indent: string.Empty);
        }

        sb.Append("public sealed record ").Append(recordName).AppendLine();
        sb.AppendLine("{");

        var props = schema.ActualProperties.ToList();
        for (var i = 0; i < props.Count; i++)
        {
            var (wireName, prop) = (props[i].Key, props[i].Value);
            var propName = ToPascalCase(wireName);
            var clrType = MapType(prop, prop.IsRequired);

            if (!string.IsNullOrEmpty(prop.Description))
            {
                AppendXmlDoc(sb, prop.Description!, indent: "    ");
            }

            sb.Append("    [JsonPropertyName(\"").Append(wireName).AppendLine("\")]");
            sb.Append("    public ").Append(clrType).Append(' ').Append(propName)
              .Append(" { get; init; }");

            // Required reference types need a null-forgiving default so the
            // nullable analyzer doesn't flag the uninitialised non-null member.
            // Required value types and all optional members are left unassigned.
            if (prop.IsRequired && IsReferenceType(clrType))
            {
                sb.Append(" = default!;");
            }

            sb.AppendLine();
            if (i < props.Count - 1)
            {
                sb.AppendLine();
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string MapType(JsonSchemaProperty prop, bool required)
    {
        var actual = prop.ActualSchema;
        string clr;

        if (actual.Type.HasFlag(JsonObjectType.Array))
        {
            var item = prop.Item?.ActualSchema;
            var itemType = item is null ? "object" : MapScalar(item);
            clr = $"IReadOnlyList<{itemType}>";
        }
        else
        {
            clr = MapScalar(actual);
        }

        var isValueType = clr is "int" or "long" or "double" or "bool";
        if (!required)
        {
            clr += isValueType ? "?" : "?";
        }

        return clr;
    }

    private static bool IsReferenceType(string clrType) =>
        clrType is "string" or "object"
        || clrType.StartsWith("IReadOnlyList<", StringComparison.Ordinal);

    private static string MapScalar(JsonSchema schema)
    {
        if (schema.Type.HasFlag(JsonObjectType.String))
        {
            return "string";
        }

        if (schema.Type.HasFlag(JsonObjectType.Integer))
        {
            return "int";
        }

        if (schema.Type.HasFlag(JsonObjectType.Number))
        {
            return "double";
        }

        if (schema.Type.HasFlag(JsonObjectType.Boolean))
        {
            return "bool";
        }

        return "object";
    }

    private static void AppendXmlDoc(StringBuilder sb, string text, string indent)
    {
        sb.Append(indent).AppendLine("/// <summary>");
        foreach (var line in text.Split('\n'))
        {
            sb.Append(indent).Append("/// ").AppendLine(System.Security.SecurityElement.Escape(line.TrimEnd('\r')));
        }

        sb.Append(indent).AppendLine("/// </summary>");
    }

    private static string ToPascalCase(string name)
    {
        var parts = name.Split(['-', '_', '.', ' '], StringSplitOptions.RemoveEmptyEntries);
        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            sb.Append(char.ToUpper(part[0], CultureInfo.InvariantCulture));
            if (part.Length > 1)
            {
                sb.Append(part[1..]);
            }
        }

        return sb.ToString();
    }
}
