// =============================================================================
// <copyright file="WireEnumVocabularyEmitter.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// =============================================================================

using System.Text;
using System.Text.Json;

namespace Strategos.Contracts.Codegen;

/// <summary>
/// Emits <c>Generated/WireEnumVocabularies.g.cs</c> — the netstandard2.0-safe
/// projection of every closed string enum in the contract (#221).
/// <para>
/// <see cref="RecordEmitter"/> already emits each of these as a net-current C#
/// <c>enum</c> with a strict <c>JsonConverter</c>, but an isolated analyzer
/// cannot reference that assembly (the documented <c>AgwfCodes.g.cs</c>
/// posture). The JSON import front-end therefore reads these slots as opaque
/// strings, and until #221 accepted any string in them. This file is the same
/// single-sourcing answer <c>AgwfCodes.g.cs</c> gave the diagnostic ids: plain
/// <c>string</c> arrays the generator <c>&lt;Compile Include&gt;</c>-links as
/// source, so the accepted set is DERIVED from the emitted schema rather than
/// re-typed in the validator.
/// </para>
/// <para>
/// Every classified enum is emitted, not a curated list: a curated list is
/// itself a place the check can go stale. Adding a member to an enum — or a new
/// closed enum — regenerates this file, and every import slot already bound to
/// that vocabulary follows without an edit.
/// </para>
/// </summary>
internal static class WireEnumVocabularyEmitter
{
    /// <summary>The file this emitter owns, under the <c>Generated/</c> directory.</summary>
    public const string FileName = "WireEnumVocabularies.g.cs";

    /// <summary>
    /// Writes the vocabulary projection for <paramref name="enumDocs"/> into
    /// <paramref name="outputDir"/>.
    /// </summary>
    /// <param name="enumDocs">Every schema classified as a closed string enum, in emission order.</param>
    /// <param name="outputDir">The <c>Generated/</c> directory.</param>
    /// <returns>A task that completes when the file is written.</returns>
    public static async Task WriteAsync(IReadOnlyList<EnumVocabulary> enumDocs, string outputDir)
    {
        var ordered = enumDocs
            .OrderBy(e => e.TypeName, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// =============================================================================");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     Generated by Strategos.Contracts.Codegen from TypeSpec-emitted JSON Schema.");
        sb.AppendLine("//     DO NOT EDIT — hand-edits are rejected by the codegen-guard CI workflow.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("// =============================================================================");
        sb.AppendLine();
        sb.AppendLine("namespace Strategos.Contracts.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Wire vocabularies of the CLOSED string enums in the contract (#221),");
        sb.AppendLine("    /// single-sourced from the emitted JSON Schema. Plain <c>string</c> arrays");
        sb.AppendLine("    /// (netstandard2.0-safe) so the isolated source generator can fail a wire");
        sb.AppendLine("    /// slot closed against the real vocabulary without referencing the");
        sb.AppendLine("    /// net-current Contracts assembly or re-typing the values.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    internal static class WireEnumVocabularies");
        sb.AppendLine("    {");

        for (var i = 0; i < ordered.Count; i++)
        {
            var vocabulary = ordered[i];
            sb.Append("        /// <summary>The ").Append(vocabulary.Values.Count)
              .Append(" wire values of the closed <c>").Append(vocabulary.TypeName)
              .AppendLine("</c> enum.</summary>");
            sb.Append("        public static readonly string[] ").Append(vocabulary.TypeName)
              .AppendLine(" = new[]");
            sb.AppendLine("        {");
            foreach (var value in vocabulary.Values)
            {
                // Serialize rather than interpolate: a schema value is any JSON string, and
                // one carrying a quote, a backslash or a newline would emit C# that does not
                // compile or that silently means something else. Same idiom as
                // RecordEmitter.AppendExactEnumConverter.
                sb.Append("            ").Append(JsonSerializer.Serialize(value)).AppendLine(",");
            }

            sb.AppendLine("        };");
            if (i < ordered.Count - 1)
            {
                sb.AppendLine();
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        await File.WriteAllTextAsync(Path.Combine(outputDir, FileName), sb.ToString()).ConfigureAwait(false);
    }

    /// <summary>One closed string enum: its generated C# type name and its wire values.</summary>
    /// <param name="TypeName">The PascalCase C# type name (e.g. <c>GateClass</c>).</param>
    /// <param name="Values">The exact wire values, in schema order.</param>
    internal sealed record EnumVocabulary(string TypeName, IReadOnlyList<string> Values);
}
