// =============================================================================
// <copyright file="StreamingExecutionMode.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// =============================================================================

namespace Strategos.Agents.Models;

/// <summary>
/// Specifies the execution mode for specialist agent responses.
/// Legacy specialist-agent surface — distinct from the <c>AgentStep</c>
/// streaming opt-in (<c>WithStreaming</c>/<c>IStreamingHandler</c>).
/// </summary>
/// <remarks>
/// <para>
/// The execution mode determines how specialist agents handle LLM responses:
/// </para>
/// <list type="bullet">
///   <item><description><see cref="Buffered"/> waits for the complete response before processing</description></item>
///   <item><description><see cref="Streaming"/> processes tokens as they arrive</description></item>
/// </list>
/// <para>
/// The default mode is <see cref="Buffered"/> for backward compatibility. Streaming mode
/// should only be enabled when real-time output is required, as it incurs additional
/// overhead for event storage and processing.
/// </para>
/// </remarks>
public enum StreamingExecutionMode
{
    /// <summary>
    /// Buffered mode - waits for the complete LLM response before processing.
    /// </summary>
    /// <remarks>
    /// This is the default mode and provides the simplest execution model.
    /// The entire response is available at once for parsing and processing.
    /// </remarks>
    Buffered = 0,

    /// <summary>
    /// Streaming mode - processes tokens as they are generated by the LLM.
    /// </summary>
    /// <remarks>
    /// <para>
    /// In streaming mode:
    /// </para>
    /// <list type="bullet">
    ///   <item><description>Tokens are emitted as <see cref="Events.StreamingTokenReceived"/> events</description></item>
    ///   <item><description>Real-time progress can be observed by clients</description></item>
    ///   <item><description>Events are stored in the progress event store for audit</description></item>
    /// </list>
    /// <para>
    /// Streaming mode is useful for long-running generations where users benefit
    /// from seeing progress, but adds overhead for event publication and storage.
    /// </para>
    /// </remarks>
    Streaming = 1
}
