// -----------------------------------------------------------------------
// <copyright file="ExtensionsEmitterUnitTests.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using Strategos.Generators.Emitters;
using Strategos.Generators.Models;

namespace Strategos.Generators.Tests.Emitters;

/// <summary>
/// Unit tests for the <see cref="ExtensionsEmitter"/> class.
/// </summary>
/// <remarks>
/// These tests verify DI extension method generation for workflow registration.
/// </remarks>
[Property("Category", "Unit")]
public class ExtensionsEmitterUnitTests
{
    // =============================================================================
    // A. File Structure Tests
    // =============================================================================

    /// <summary>
    /// Verifies that the emitter generates auto-generated header.
    /// </summary>
    [Test]
    public async Task Emit_WithValidModel_IncludesAutoGeneratedHeader()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("// <auto-generated/>");
    }

    /// <summary>
    /// Verifies that the emitter includes nullable enable directive.
    /// </summary>
    [Test]
    public async Task Emit_WithValidModel_IncludesNullableEnable()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("#nullable enable");
    }

    /// <summary>
    /// Verifies that the emitter uses the correct namespace.
    /// </summary>
    [Test]
    public async Task Emit_WithValidModel_UsesCorrectNamespace()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("namespace TestNamespace;");
    }

    /// <summary>
    /// Verifies that the emitter includes required usings.
    /// </summary>
    [Test]
    public async Task Emit_WithValidModel_IncludesRequiredUsings()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("using Microsoft.Extensions.DependencyInjection;");
    }

    // =============================================================================
    // B. Extension Class Tests
    // =============================================================================

    /// <summary>
    /// Verifies that the emitter generates an extensions class with correct name.
    /// </summary>
    [Test]
    public async Task Emit_WithValidModel_GeneratesExtensionsClass()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("public static partial class ProcessOrderWorkflowExtensions");
    }

    /// <summary>
    /// Verifies that the extensions class is static.
    /// </summary>
    [Test]
    public async Task Emit_ExtensionsClass_IsStatic()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("public static partial class");
    }

    /// <summary>
    /// Verifies that the extensions class has XML documentation.
    /// </summary>
    [Test]
    public async Task Emit_ExtensionsClass_IncludesXmlDocumentation()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("/// <summary>");
        await Assert.That(source).Contains("process-order workflow");
    }

    // =============================================================================
    // C. Add Method Tests
    // =============================================================================

    /// <summary>
    /// Verifies that the emitter generates an Add extension method.
    /// </summary>
    [Test]
    public async Task Emit_WithValidModel_GeneratesAddMethod()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("AddProcessOrderWorkflow(");
    }

    /// <summary>
    /// Verifies that the Add method is an extension method on IServiceCollection.
    /// </summary>
    [Test]
    public async Task Emit_AddMethod_IsExtensionMethod()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("this IServiceCollection services");
    }

    /// <summary>
    /// Verifies that the Add method returns IServiceCollection for chaining.
    /// </summary>
    [Test]
    public async Task Emit_AddMethod_ReturnsServiceCollection()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("public static IServiceCollection Add");
        await Assert.That(source).Contains("return services;");
    }

    /// <summary>
    /// Verifies that the Add method has guard clause.
    /// </summary>
    [Test]
    public async Task Emit_AddMethod_HasGuardClause()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("ArgumentNullException.ThrowIfNull(services");
    }

    // =============================================================================
    // D. Step Registration Tests
    // =============================================================================

    /// <summary>
    /// Verifies that all steps are registered as transient.
    /// </summary>
    [Test]
    public async Task Emit_AddMethod_RegistersStepsAsTransient()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("services.AddTransient<ValidateOrder>();");
        await Assert.That(source).Contains("services.AddTransient<ProcessPayment>();");
        await Assert.That(source).Contains("services.AddTransient<SendConfirmation>();");
    }

    // =============================================================================
    // E. Handler Registration Tests
    // =============================================================================

    /// <summary>
    /// Verifies that all worker handlers are registered as transient.
    /// </summary>
    [Test]
    public async Task Emit_AddMethod_RegistersHandlersAsTransient()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("services.AddTransient<ValidateOrderHandler>();");
        await Assert.That(source).Contains("services.AddTransient<ProcessPaymentHandler>();");
        await Assert.That(source).Contains("services.AddTransient<SendConfirmationHandler>();");
    }

    // =============================================================================
    // F. Workflow Definition Evaluation Tests
    // =============================================================================

    /// <summary>
    /// Verifies that the Add method evaluates the workflow definition to register loop conditions.
    /// </summary>
    [Test]
    public async Task Emit_AddMethod_ForcesDefinitionEvaluation()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("_ = ProcessOrderWorkflowDefinition.Definition;");
    }

    /// <summary>
    /// Verifies that the Definition evaluation has explanatory comment.
    /// </summary>
    [Test]
    public async Task Emit_AddMethod_IncludesDefinitionEvaluationComment()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = ExtensionsEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("// Force evaluation of workflow definition to register loop conditions");
    }

    // =============================================================================
    // G. Guard Clause Tests
    // =============================================================================

    /// <summary>
    /// Verifies that null model throws ArgumentNullException.
    /// </summary>
    [Test]
    public async Task Emit_WithNullModel_ThrowsArgumentNullException()
    {
        // Arrange & Act & Assert
        await Assert.That(() => ExtensionsEmitter.Emit(null!))
            .Throws<ArgumentNullException>();
    }

    // =============================================================================
    // Helper Methods
    // =============================================================================

    private static WorkflowModel CreateTestModel()
    {
        return new WorkflowModel(
            WorkflowName: "process-order",
            PascalName: "ProcessOrder",
            Namespace: "TestNamespace",
            StepNames: ["ValidateOrder", "ProcessPayment", "SendConfirmation"],
            StateTypeName: "OrderState");
    }
}
