// -----------------------------------------------------------------------
// <copyright file="WorkerHandlerEmitterUnitTests.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using Strategos.Generators.Emitters;
using Strategos.Generators.Models;

namespace Strategos.Generators.Tests.Emitters;

/// <summary>
/// Unit tests for the <see cref="WorkerHandlerEmitter"/> class.
/// </summary>
/// <remarks>
/// These tests verify worker handler generation following the Brain &amp; Muscle pattern.
/// Workers execute steps (Muscle) while Sagas manage state transitions (Brain).
/// </remarks>
[Property("Category", "Unit")]
public class WorkerHandlerEmitterUnitTests
{
    // =============================================================================
    // A. File Structure Tests
    // =============================================================================

    /// <summary>
    /// Verifies that the emitter generates auto-generated header.
    /// </summary>
    [Test]
    public async Task Emit_WithValidModel_IncludesAutoGeneratedHeader()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("// <auto-generated/>");
    }

    /// <summary>
    /// Verifies that the emitter includes nullable enable directive.
    /// </summary>
    [Test]
    public async Task Emit_WithValidModel_IncludesNullableEnable()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("#nullable enable");
    }

    /// <summary>
    /// Verifies that the emitter uses the correct namespace.
    /// </summary>
    [Test]
    public async Task Emit_WithValidModel_UsesCorrectNamespace()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("namespace TestNamespace;");
    }

    // =============================================================================
    // B. Handler Class Generation Tests
    // =============================================================================

    /// <summary>
    /// Verifies that a handler class is generated for each step.
    /// </summary>
    [Test]
    public async Task Emit_LinearWorkflow_GeneratesHandlerPerStep()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert - handlers are now sealed partial classes
        await Assert.That(source).Contains("public sealed partial class ValidateOrderHandler");
        await Assert.That(source).Contains("public sealed partial class ProcessPaymentHandler");
        await Assert.That(source).Contains("public sealed partial class SendConfirmationHandler");
    }

    /// <summary>
    /// Verifies that handlers inject the step type and ILogger via constructor.
    /// </summary>
    [Test]
    public async Task Emit_Handler_InjectsStepAndLoggerViaConstructor()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert - Primary constructor with step and ILogger parameters
        await Assert.That(source).Contains("ValidateOrderHandler(");
        await Assert.That(source).Contains("ValidateOrder step,");
        await Assert.That(source).Contains("ILogger<ValidateOrderHandler> logger)");
    }

    /// <summary>
    /// Verifies that handlers have XML documentation.
    /// </summary>
    [Test]
    public async Task Emit_Handler_IncludesXmlDocumentation()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("/// <summary>");
        await Assert.That(source).Contains("/// Worker handler for the ValidateOrder step");
    }

    // =============================================================================
    // C. Handle Method Tests
    // =============================================================================

    /// <summary>
    /// Verifies that handlers have a Handle method for the worker command.
    /// </summary>
    [Test]
    public async Task Emit_Handler_HasHandleMethodForWorkerCommand()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert - Handle method accepts the worker command (line break in signature)
        await Assert.That(source).Contains("ExecuteValidateOrderWorkerCommand command");
    }

    /// <summary>
    /// Verifies that Handle method is async.
    /// </summary>
    [Test]
    public async Task Emit_Handler_HandleMethodIsAsync()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("public async Task<ValidateOrderCompleted> Handle(");
    }

    /// <summary>
    /// Verifies that Handle method returns the completion event.
    /// </summary>
    [Test]
    public async Task Emit_Handler_HandleMethodReturnsCompletedEvent()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("return new ValidateOrderCompleted(");
    }

    /// <summary>
    /// Verifies that Handle method supports CancellationToken.
    /// </summary>
    [Test]
    public async Task Emit_Handler_HandleMethodAcceptsCancellationToken()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("CancellationToken ct");
    }

    // =============================================================================
    // D. Step Execution Tests
    // =============================================================================

    /// <summary>
    /// Verifies that Handle method creates a StepContext.
    /// </summary>
    [Test]
    public async Task Emit_Handler_CreatesStepContext()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert - variable name is stepContext
        await Assert.That(source).Contains("var stepContext = StepContext.Create(");
    }

    /// <summary>
    /// Verifies that Handle method calls ExecuteAsync on the step.
    /// </summary>
    [Test]
    public async Task Emit_Handler_CallsStepExecuteAsync()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("_step.ExecuteAsync(");
    }

    /// <summary>
    /// Verifies that Handle method passes state from command to step.
    /// </summary>
    [Test]
    public async Task Emit_Handler_PassesStateToStep()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("command.State");
    }

    /// <summary>
    /// Verifies that completion event includes workflow ID.
    /// </summary>
    [Test]
    public async Task Emit_Handler_CompletionEventIncludesWorkflowId()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("command.WorkflowId");
    }

    /// <summary>
    /// Verifies that completion event includes updated state.
    /// </summary>
    [Test]
    public async Task Emit_Handler_CompletionEventIncludesUpdatedState()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("result.UpdatedState");
    }

    // =============================================================================
    // E. Guard Clause Tests
    // =============================================================================

    /// <summary>
    /// Verifies that null model throws ArgumentNullException.
    /// </summary>
    [Test]
    public async Task Emit_WithNullModel_ThrowsArgumentNullException()
    {
        // Arrange & Act & Assert
        await Assert.That(() => WorkerHandlerEmitter.Emit(null!))
            .Throws<ArgumentNullException>();
    }

    /// <summary>
    /// Verifies that Handle method validates command argument.
    /// </summary>
    [Test]
    public async Task Emit_Handler_ValidatesCommandArgument()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert
        await Assert.That(source).Contains("ArgumentNullException.ThrowIfNull(command");
    }

    // =============================================================================
    // F. Step Type Reference Tests
    // =============================================================================

    /// <summary>
    /// Verifies that handlers reference step interface correctly.
    /// </summary>
    [Test]
    public async Task Emit_Handler_ReferencesStepInterface()
    {
        // Arrange
        var model = CreateTestModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert - Handler should use concrete step type injected by DI
        await Assert.That(source).Contains("private readonly ValidateOrder _step");
    }

    // =============================================================================
    // G. Instance Name Tests (Phase 2 - Handler Deduplication)
    // =============================================================================

    /// <summary>
    /// Verifies that only ONE handler is generated per step TYPE, even when same type
    /// is used with different instance names. Handlers are shared (deduped by StepName).
    /// </summary>
    /// <remarks>
    /// This test ensures that Wolverine's message-type-based routing works correctly.
    /// All instances of AnalyzeStep share the same handler class.
    /// </remarks>
    [Test]
    public async Task Emit_WithInstanceNames_GeneratesOneHandlerPerType()
    {
        // Arrange - Same step type (AnalyzeStep) with different instance names
        var steps = new List<StepModel>
        {
            StepModel.Create("PrepareData", "TestNamespace.PrepareData"),
            StepModel.Create("AnalyzeStep", "TestNamespace.AnalyzeStep", instanceName: "Technical"),
            StepModel.Create("AnalyzeStep", "TestNamespace.AnalyzeStep", instanceName: "Fundamental"),
            StepModel.Create("SynthesizeResults", "TestNamespace.SynthesizeResults"),
        };

        var model = new WorkflowModel(
            WorkflowName: "multi-analysis",
            PascalName: "MultiAnalysis",
            Namespace: "TestNamespace",
            StepNames: ["PrepareData", "Technical", "Fundamental", "SynthesizeResults"],
            StateTypeName: "AnalysisState",
            Steps: steps);

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert - Should have ONE AnalyzeStepHandler, not TechnicalHandler/FundamentalHandler
        await Assert.That(source).Contains("AnalyzeStepHandler");
        await Assert.That(source).DoesNotContain("TechnicalHandler");
        await Assert.That(source).DoesNotContain("FundamentalHandler");

        // Count occurrences of AnalyzeStepHandler - should appear only once as class definition
        // (may appear multiple times in comments/references, but class def should be once)
        var classDefinitionCount = CountOccurrences(source, "public sealed partial class AnalyzeStepHandler");
        await Assert.That(classDefinitionCount).IsEqualTo(1);
    }

    /// <summary>
    /// Verifies that handlers use step TYPE name for command/event types.
    /// </summary>
    [Test]
    public async Task Emit_WithInstanceNames_UsesStepTypeForCommandsAndEvents()
    {
        // Arrange
        var steps = new List<StepModel>
        {
            StepModel.Create("AnalyzeStep", "TestNamespace.AnalyzeStep", instanceName: "Technical"),
            StepModel.Create("AnalyzeStep", "TestNamespace.AnalyzeStep", instanceName: "Fundamental"),
        };

        var model = new WorkflowModel(
            WorkflowName: "multi-analysis",
            PascalName: "MultiAnalysis",
            Namespace: "TestNamespace",
            StepNames: ["Technical", "Fundamental"],
            StateTypeName: "AnalysisState",
            Steps: steps);

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert - Commands and events use step TYPE name
        await Assert.That(source).Contains("ExecuteAnalyzeStepWorkerCommand");
        await Assert.That(source).Contains("AnalyzeStepCompleted");

        // Should NOT have instance-name-based commands/events
        await Assert.That(source).DoesNotContain("ExecuteTechnicalWorkerCommand");
        await Assert.That(source).DoesNotContain("TechnicalCompleted");
    }

    // =============================================================================
    // M. OnFailure Worker Handler Tests (#140 Task 3.1)
    // =============================================================================

    /// <summary>
    /// Verifies that a workflow with an OnFailure chain emits a dedicated worker
    /// handler that handles the saga-dispatched
    /// <c>ExecuteFailureHandler_{id}_{step}WorkerCommand</c> and returns the
    /// <c>FailureHandler_{id}_{step}Completed</c> event. This is the previously-dead
    /// receiver that left the OnFailure chain unrunnable.
    /// </summary>
    [Test]
    public async Task Emit_WorkflowWithOnFailure_EmitsFailureHandlerWorkerHandle()
    {
        // Arrange
        var model = CreateOnFailureModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert - a dedicated FailureHandler_{id}_{step}Handler class exists
        await Assert.That(source).Contains("class FailureHandler_recovery_NotifyFailureHandler");

        // It HANDLES the saga-dispatched failure-handler worker command...
        await Assert.That(source).Contains("ExecuteFailureHandler_recovery_NotifyFailureWorkerCommand command,");

        // ...and RETURNS the failure-handler completed event the saga folds and routes on.
        await Assert.That(source).Contains("Task<FailureHandler_recovery_NotifyFailureCompleted> Handle");
        await Assert.That(source).Contains("return new FailureHandler_recovery_NotifyFailureCompleted(");

        // It executes the OnFailure step.
        await Assert.That(source).Contains("await _step.ExecuteAsync(command.State, stepContext, ct)");
    }

    /// <summary>
    /// Verifies that a main-flow step in a workflow with an OnFailure chain lowers a
    /// trigger-publishing <c>Configure(HandlerChain)</c> so a thrown step routes into
    /// the OnFailure chain at runtime (the previously-missing publish for a
    /// non-compensated failing step).
    /// </summary>
    [Test]
    public async Task Emit_WorkflowWithOnFailure_MainFlowStep_PublishesTrigger()
    {
        // Arrange
        var model = CreateOnFailureModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert - the main-flow step's error chain publishes the trigger command.
        await Assert.That(source).Contains("public static void Configure(HandlerChain chain)");
        await Assert.That(source).Contains("bus.PublishAsync(new TriggerOnFailureProofFailureHandlerCommand(");
        await Assert.That(source).Contains("// routes to OnFailure chain");
    }

    /// <summary>
    /// Verifies that the OnFailure handler step itself does NOT publish the trigger
    /// (it is the recovery path and must not re-trigger the OnFailure chain).
    /// </summary>
    [Test]
    public async Task Emit_WorkflowWithOnFailure_HandlerStep_DoesNotPublishTrigger()
    {
        // Arrange
        var model = CreateOnFailureModel();

        // Act
        var source = WorkerHandlerEmitter.Emit(model);

        // Assert - the NotifyFailure step's plain main-flow handler has no Configure
        // that publishes the trigger; only the dedicated failure-handler worker class
        // references NotifyFailure as a recovery step. Confirm exactly the main-flow
        // steps (ValidateOrder) carry the trigger publish but the OnFailure step's
        // dedicated worker class never publishes a trigger.
        const string notifyWorkerDecl = "class FailureHandler_recovery_NotifyFailureHandler";
        var notifyWorkerStart = source.IndexOf(notifyWorkerDecl, StringComparison.Ordinal);
        await Assert.That(notifyWorkerStart).IsGreaterThan(-1);

        // Scope the negative assertion to THIS class body only: slice to the next
        // class declaration (or EOF) so a trigger publish in any LATER generated
        // class cannot false-fail the assertion on the NotifyFailure handler.
        var nextClassStart = source.IndexOf(
            "class ",
            notifyWorkerStart + notifyWorkerDecl.Length,
            StringComparison.Ordinal);
        var notifyWorkerBody = nextClassStart > -1
            ? source.Substring(notifyWorkerStart, nextClassStart - notifyWorkerStart)
            : source.Substring(notifyWorkerStart);
        await Assert.That(notifyWorkerBody).DoesNotContain("PublishAsync(new TriggerOnFailureProofFailureHandlerCommand");
    }

    // =============================================================================
    // N. Path-qualified fork worker handles (T1b / Option B)
    // =============================================================================

    /// <summary>
    /// Shared-type fork path-ends keep one handler class per type with Handle
    /// overloads that return the phase-named completed events.
    /// </summary>
    [Test]
    public async Task Emit_SharedTypeForkPathEnds_HandleOverloadsReturnPhaseNamedEvents()
    {
        var source = WorkerHandlerEmitter.Emit(ForkPathMessageFixtures.SharedTypeInstanceNamed());

        await Assert.That(CountOccurrences(source, "public sealed partial class AnalyzeStepHandler")).IsEqualTo(1);
        await Assert.That(source).Contains("public async Task<TechnicalCompleted> Handle(");
        await Assert.That(source).Contains("ExecuteTechnicalWorkerCommand command");
        await Assert.That(source).Contains("return new TechnicalCompleted(");
        await Assert.That(source).Contains("public async Task<FundamentalCompleted> Handle(");
        await Assert.That(source).Contains("ExecuteFundamentalWorkerCommand command");
        await Assert.That(source).Contains("return new FundamentalCompleted(");
        await Assert.That(source).DoesNotContain("Task<AnalyzeStepCompleted> Handle");
        await Assert.That(source).DoesNotContain("TechnicalHandler");
        await Assert.That(source).DoesNotContain("FundamentalHandler(");
    }

    /// <summary>
    /// Colliding phase names bind Handle to path-qualified command and event types.
    /// </summary>
    [Test]
    public async Task Emit_SharedPhaseNameForkPathEnds_HandleOverloadsUsePathQualifiedTypes()
    {
        var source = WorkerHandlerEmitter.Emit(ForkPathMessageFixtures.SharedPhaseName());

        await Assert.That(source).Contains("public async Task<Path0_AnalyzeStepCompleted> Handle(");
        await Assert.That(source).Contains("ExecutePath0_AnalyzeStepWorkerCommand command");
        await Assert.That(source).Contains("return new Path0_AnalyzeStepCompleted(");
        await Assert.That(source).Contains("public async Task<Path1_AnalyzeStepCompleted> Handle(");
        await Assert.That(source).Contains("ExecutePath1_AnalyzeStepWorkerCommand command");
        await Assert.That(source).DoesNotContain("Task<AnalyzeStepCompleted> Handle");
    }

    /// <summary>
    /// Unique-type fork paths keep the type-level Handle signature.
    /// </summary>
    [Test]
    public async Task Emit_UniqueTypeForkPaths_KeepsTypeLevelHandle()
    {
        var source = WorkerHandlerEmitter.Emit(ForkPathMessageFixtures.UniqueTypes());

        await Assert.That(source).Contains("public async Task<TechnicalAnalyzeStepCompleted> Handle(");
        await Assert.That(source).Contains("ExecuteTechnicalAnalyzeStepWorkerCommand command");
        await Assert.That(source).Contains("public async Task<FundamentalAnalyzeStepCompleted> Handle(");
        await Assert.That(source).DoesNotContain("ExecutePath0_");
    }

    /// <summary>
    /// Wolverine builds one <c>HandlerChain</c> per message type and invokes the handler
    /// type's static <c>Configure</c> for EACH of them, so a handler class with a Handle
    /// overload per path-qualified command needs an error policy per command. A single
    /// <c>CompensatingAction&lt;T&gt;</c> pinned to one command silently no-ops on every
    /// sibling chain (its runtime <c>is T</c> cast fails), and the failure-handler trigger
    /// is never published for those paths.
    /// </summary>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    public async Task Emit_SharedPhaseNameForkPathEnds_ConfiguresEveryQualifiedCommand()
    {
        var source = WorkerHandlerEmitter.Emit(ForkPathMessageFixtures.SharedPhaseNameWithCompensation());

        // One Configure, dispatching on the chain's own message type ...
        await Assert.That(CountOccurrences(source, "public static void Configure(HandlerChain chain)")).IsEqualTo(1);
        await Assert.That(source).Contains("if (chain.MessageType == typeof(ExecutePath0_AnalyzeStepWorkerCommand))");
        await Assert.That(source).Contains("if (chain.MessageType == typeof(ExecutePath1_AnalyzeStepWorkerCommand))");

        // ... with the compensating action typed to the command that chain actually carries.
        await Assert.That(source).Contains(".CompensatingAction<ExecutePath0_AnalyzeStepWorkerCommand>(");
        await Assert.That(source).Contains(".CompensatingAction<ExecutePath1_AnalyzeStepWorkerCommand>(");
    }

    /// <summary>
    /// A handler class with a single command type keeps the undispatched policy shape —
    /// the per-message-type guard is only introduced where there is something to dispatch.
    /// </summary>
    /// <returns>A task representing the asynchronous test.</returns>
    [Test]
    public async Task Emit_SingleCommandStep_ConfigureHasNoMessageTypeDispatch()
    {
        var source = WorkerHandlerEmitter.Emit(CreateOnFailureModel());

        await Assert.That(source).Contains("public static void Configure(HandlerChain chain)");
        await Assert.That(source).DoesNotContain("chain.MessageType == typeof(");
    }

    // =============================================================================
    // Helper Methods
    // =============================================================================

    private static WorkflowModel CreateOnFailureModel()
    {
        var handler = FailureHandlerModel.Create(
            handlerId: "recovery",
            scope: FailureHandlerScope.Workflow,
            stepNames: ["NotifyFailure"],
            isTerminal: true,
            steps: [StepModel.Create("NotifyFailure", "TestNamespace.NotifyFailure")]);

        var steps = new List<StepModel>
        {
            StepModel.Create("ValidateOrder", "TestNamespace.ValidateOrder"),
            StepModel.Create("NotifyFailure", "TestNamespace.NotifyFailure"),
        };

        return new WorkflowModel(
            WorkflowName: "on-failure-proof",
            PascalName: "OnFailureProof",
            Namespace: "TestNamespace",
            StepNames: ["ValidateOrder", "NotifyFailure"],
            StateTypeName: "OrderState",
            Steps: steps,
            FailureHandlers: [handler]);
    }

    private static WorkflowModel CreateTestModel()
    {
        return new WorkflowModel(
            WorkflowName: "process-order",
            PascalName: "ProcessOrder",
            Namespace: "TestNamespace",
            StepNames: ["ValidateOrder", "ProcessPayment", "SendConfirmation"],
            StateTypeName: "OrderState");
    }

    private static int CountOccurrences(string source, string pattern)
    {
        var count = 0;
        var index = 0;
        while ((index = source.IndexOf(pattern, index, StringComparison.Ordinal)) != -1)
        {
            count++;
            index += pattern.Length;
        }

        return count;
    }
}
