using System.Text.Json;

namespace Strategos.Contracts.Tests.Zod;

/// <summary>
/// #219 — Strategos owns the TypeScript/Zod projection of its own contracts.
/// </summary>
/// <remarks>
/// The claim these tests defend is not "a Zod file exists". It is that the
/// emitted artifact is derived from the TypeSpec sources, is checked by the same
/// codegen guard as every other emitted target, carries the referential rules
/// core JSON Schema cannot express, and reaches the SAME verdict as the .NET
/// import front-end on the documents both read. A consumer that pins this
/// artifact writes no <c>superRefine</c> of its own, which is the whole point:
/// a drift gate that runs in the consumer's repository protects the consumer,
/// not the contract.
/// </remarks>
public sealed class ZodProjectionTests
{
    private static string ZodDir => Path.Combine(
        RepoLayout.ContractsProjectDir, "Generated", "zod");

    private static string SchemaDir => Path.Combine(
        RepoLayout.ContractsProjectDir, "schemas", "json-schema");

    /// <summary>
    /// One module per emitted schema, plus the reference runtime and the barrel.
    /// A missing module is a consumer that cannot import a shape the contract
    /// declares; an extra one is an orphan the emitter failed to stale-clean.
    /// </summary>
    [Test]
    public async Task Projection_EmitsOneModulePerSchema_PlusTheReferenceRuntime()
    {
        var schemas = Directory.EnumerateFiles(SchemaDir, "*.json")
            .Select(path => Path.GetFileNameWithoutExtension(path))
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();
        var modules = Directory.EnumerateFiles(ZodDir, "*.ts")
            .Select(path => Path.GetFileNameWithoutExtension(path))
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();

        await Assert.That(modules).Contains("_references")
            .Because("the reference rules are lowered against a shared runtime walker.");
        await Assert.That(modules).Contains("index")
            .Because("consumers import the barrel, not 185 module paths.");

        var schemaModules = modules
            .Where(name => name is not ("_references" or "index"))
            .ToArray();
        await Assert.That(schemaModules).IsEquivalentTo(schemas)
            .Because("every emitted JSON Schema has exactly one Zod module, and no module outlives its schema.");
    }

    /// <summary>
    /// The emitted modules carry the auto-generated banner. This is what makes a
    /// hand-edit visible as an intent, not just as a codegen-guard diff.
    /// </summary>
    [Test]
    public async Task Projection_StampsEveryModuleAsEmitterOwned()
    {
        foreach (var module in Directory.EnumerateFiles(ZodDir, "*.ts"))
        {
            var text = await File.ReadAllTextAsync(module);
            var head = text[..Math.Min(400, text.Length)];
            await Assert.That(head).Contains("<auto-generated>")
                .Because($"{Path.GetFileName(module)} is emitter-owned output.");
            await Assert.That(head).Contains("emit-zod.mjs")
                .Because($"{Path.GetFileName(module)} must name the emitter that produced it.");
        }
    }

    /// <summary>
    /// The three declared reference rules reach the emitted artifact, attached to
    /// the root document that owns each collection.
    /// </summary>
    /// <remarks>
    /// The rules are not written here — they are read off <c>@references</c> in
    /// the TypeSpec. Asserting them at the artifact is how a rule that is
    /// declared but never lowered (the failure this whole path exists to
    /// prevent) becomes visible.
    /// </remarks>
    [Test]
    public async Task Projection_LowersEveryDeclaredReferenceRule_OntoItsRootDocument()
    {
        var root = await File.ReadAllTextAsync(Path.Combine(ZodDir, "WorkflowDefinitionV1.ts"));

        await Assert.That(root).Contains("superRefine(referenceRules(")
            .Because("the root document carries the referential checks for the rules declared beneath it.");
        await Assert.That(root).Contains("\"owner\": \"GateStep\"");
        await Assert.That(root).Contains("\"property\": \"gateId\"");
        await Assert.That(root).Contains("\"owner\": \"TransitionDefinition\"");
        await Assert.That(root).Contains("\"property\": \"fromStepId\"");
        await Assert.That(root).Contains("\"property\": \"toStepId\"");

        // The declaration is the source of the rule. If TypeSpec declares a
        // reference the artifact does not carry, the artifact is stale.
        var declared = Directory.EnumerateFiles(SchemaDir, "*.json")
            .SelectMany(DeclaredReferences)
            .OrderBy(entry => entry, StringComparer.Ordinal)
            .ToArray();
        await Assert.That(declared).IsEquivalentTo(
            ["GateStep.gateId", "TransitionDefinition.fromStepId", "TransitionDefinition.toStepId"])
            .Because("a @references declaration added to the TypeSpec must be lowered, not silently ignored.");
    }

    /// <summary>
    /// The emitted projection type-checks, accepts the whole #53 builder corpus,
    /// and rejects both declared reference violations — including the exact
    /// document AGWF032 rejects, at the exact position AGWF032 reports.
    /// </summary>
    /// <remarks>
    /// This runs the artifact rather than reading it. The gate compiles
    /// <c>Generated/zod</c> with <c>tsc</c> and executes the result, so a schema
    /// that only looks right fails here.
    /// </remarks>
    [Test]
    [NotInParallel("zod-conformance")]
    public async Task Projection_AcceptsTheCorpus_AndRejectsEveryDeclaredReferenceViolation()
    {
        await TspToolchain.EnsureRestoredAsync();
        var fixtures = await BuilderFixtures.EnsureExportedAsync();

        var result = await Cli.RunAsync(
            "node",
            $"scripts/verify-zod-conformance.mjs \"{fixtures}\"",
            RepoLayout.ContractsProjectDir);

        await Assert.That(result.ExitCode).IsEqualTo(0)
            .Because($"the emitted Zod must agree with the .NET arm on every corpus document:\n{result.Output}");
        await Assert.That(result.Output).Contains("rejected dangling-gate.workflow.json at $.steps[1].gateId")
            .Because("the declared gateId rule must fire where the hand-coded AGWF032 check fires.");
        await Assert.That(result.Output).Contains("rejected a dangling transition fromStepId");
        await Assert.That(result.Output).Contains("rejected a dangling transition toStepId");
    }

    /// <summary>
    /// The emitter stops on a JSON Schema keyword it does not lower.
    /// </summary>
    /// <remarks>
    /// This is the property no corpus can establish. Every fixture in the corpus
    /// is VALID, so a dropped constraint — an emitter that meets
    /// <c>exclusiveMinimum</c> and quietly ignores it — produces a Zod schema
    /// that accepts documents the contract rejects, and the corpus still passes.
    /// Failing closed on an unknown keyword is what makes the corpus result mean
    /// something.
    /// </remarks>
    [Test]
    [NotInParallel("zod-conformance")]
    public async Task Emitter_FailsClosed_OnAJsonSchemaKeywordItDoesNotLower()
    {
        await TspToolchain.EnsureRestoredAsync();
        var probeDir = Directory.CreateTempSubdirectory("contracts-zod-unknown-keyword-").FullName;
        var schemas = Path.Combine(probeDir, "schemas", "json-schema");
        var output = Path.Combine(probeDir, "out");
        Directory.CreateDirectory(schemas);

        try
        {
            await File.WriteAllTextAsync(Path.Combine(schemas, "Probe.json"), """
                {
                  "$schema": "https://json-schema.org/draft/2020-12/schema",
                  "$id": "Probe.json",
                  "type": "object",
                  "properties": {
                    "value": { "type": "integer", "exclusiveMinimum": 0 }
                  },
                  "required": ["value"]
                }
                """);

            // The emitter reads its schema directory relative to its own location,
            // so it is copied next to the probe schemas rather than pointed at them.
            var emitter = Path.Combine(probeDir, "scripts");
            Directory.CreateDirectory(emitter);
            File.Copy(
                Path.Combine(RepoLayout.ContractsProjectDir, "scripts", "emit-zod.mjs"),
                Path.Combine(emitter, "emit-zod.mjs"));

            var result = await Cli.RunAsync(
                "node", $"scripts/emit-zod.mjs \"{output}\"", probeDir);

            await Assert.That(result.ExitCode).IsNotEqualTo(0)
                .Because($"an unlowered keyword must stop the emit, not be dropped:\n{result.Output}");
            await Assert.That(result.Output).Contains("exclusiveMinimum")
                .Because("the emitter must name the keyword it cannot lower.");
            await Assert.That(Directory.Exists(output) && Directory.EnumerateFiles(output).Any()).IsFalse()
                .Because("a stopped emit must not leave a partial projection behind.");
        }
        finally
        {
            Directory.Delete(probeDir, recursive: true);
        }
    }

    /// <summary>
    /// <c>@references</c> rejects bad authoring at <c>tsp compile</c> time, with
    /// its own library diagnostic — before anything is emitted.
    /// </summary>
    /// <remarks>
    /// A rule that is only checked by the emitter is checked too late: the bad
    /// declaration is already in the TypeSpec, and the person who wrote it has
    /// moved on. All three rejections fire in one compile so a fix for one does
    /// not hide the others.
    /// </remarks>
    [Test]
    [NotInParallel("tsp-compile")]
    public async Task ReferencesDecorator_RejectsBadAuthoring_BeforeEmission()
    {
        var sourcePath = Path.Combine(
            RepoLayout.ContractsProjectDir, $".invalid-references-{Guid.NewGuid():N}.tsp");
        var output = Directory.CreateTempSubdirectory("contracts-invalid-references-").FullName;

        try
        {
            await File.WriteAllTextAsync(sourcePath, """
                import "./main.tsp";

                using LevelUp.Strategos.Contracts;

                model UnrootedCollectionFixture {
                  @references("gates", "id")
                  danglingCollection: string;
                }

                model BlankIdFieldFixture {
                  @references("/gates", "   ")
                  blankIdField: string;
                }

                model NonStringTargetFixture {
                  @references("/gates", "id")
                  typedHandle: int32;
                }
                """);

            var result = await Cli.RunAsync(
                "npx",
                $"tsp compile \"{sourcePath}\" --output-dir \"{output}\"",
                RepoLayout.ContractsProjectDir);

            await Assert.That(result.ExitCode).IsNotEqualTo(0)
                .Because($"bad @references authoring must not compile:\n{result.Output}");
            await Assert.That(result.Output).Contains("contract-references-collection")
                .Because("a collection that is not a root-anchored pointer cannot be resolved to a root document.");
            await Assert.That(result.Output).Contains("contract-references-id-field")
                .Because("a blank id field matches nothing, so the rule would never fire.");
            await Assert.That(result.Output).Contains("contract-references-target-type")
                .Because("a reference is a string moniker, never a typed handle (INV-8).");
        }
        finally
        {
            File.Delete(sourcePath);
            Directory.Delete(output, recursive: true);
        }
    }

    /// <summary>Every <c>@references</c> declaration in one emitted schema document.</summary>
    private static IEnumerable<string> DeclaredReferences(string schemaPath)
    {
        using var document = JsonDocument.Parse(File.ReadAllText(schemaPath));
        if (!document.RootElement.TryGetProperty("properties", out var properties))
        {
            yield break;
        }

        var owner = Path.GetFileNameWithoutExtension(schemaPath);
        foreach (var property in properties.EnumerateObject())
        {
            if (property.Value.TryGetProperty("x-strategos-references-v1", out _))
            {
                yield return $"{owner}.{property.Name}";
            }
        }
    }
}
