// -----------------------------------------------------------------------
// <copyright file="ApprovalIntegrationHandlerEmitter.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System.Text;

using Strategos.Generators.Models;
using Strategos.Generators.Polyfills;

namespace Strategos.Generators.Emitters;

/// <summary>
/// Emits a Wolverine handler class that bridges saga approval events to IHumanApprovalHandler.
/// </summary>
/// <remarks>
/// <para>
/// This emitter generates a handler that:
/// <list type="bullet">
///   <item><description>Receives RequestApprovalEvent from the saga</description></item>
///   <item><description>Creates an ApprovalRequest and submits to IHumanApprovalHandler</description></item>
///   <item><description>Schedules a timeout command via Wolverine</description></item>
///   <item><description>Returns SetPendingApprovalCommand to update saga state</description></item>
/// </list>
/// </para>
/// </remarks>
internal sealed class ApprovalIntegrationHandlerEmitter
{
    /// <summary>
    /// Emits the approval integration handler for the workflow.
    /// </summary>
    /// <param name="sb">The <see cref="StringBuilder"/> to append generated code to.</param>
    /// <param name="model">The workflow model.</param>
    /// <exception cref="ArgumentNullException">
    /// Thrown when <paramref name="sb"/> or <paramref name="model"/> is null.
    /// </exception>
    public void Emit(StringBuilder sb, WorkflowModel model)
    {
        ThrowHelper.ThrowIfNull(sb, nameof(sb));
        ThrowHelper.ThrowIfNull(model, nameof(model));

        // Only emit if there are approval points
        if (!model.HasApprovalPoints)
        {
            return;
        }

        EmitFileHeader(sb, model);
        EmitClassHeader(sb, model);
        EmitConstructor(sb, model);

        // Emit handler for each approval point
        foreach (var approval in model.ApprovalPoints!)
        {
            sb.AppendLine();
            EmitApprovalHandler(sb, model, approval);
        }

        EmitClassFooter(sb);
    }

    private static void EmitFileHeader(StringBuilder sb, WorkflowModel model)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine("using Strategos.Abstractions;");
        sb.AppendLine("using Strategos.Models;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using Wolverine;");
        sb.AppendLine();
    }

    private static void EmitClassHeader(StringBuilder sb, WorkflowModel model)
    {
        var className = $"{model.PascalName}ApprovalIntegrationHandler";

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Handles approval request events for the {model.WorkflowName} workflow.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly IHumanApprovalHandler _approvalHandler;");
        sb.AppendLine($"    private readonly ILogger<{className}> _logger;");
        sb.AppendLine();
    }

    private static void EmitConstructor(StringBuilder sb, WorkflowModel model)
    {
        var className = $"{model.PascalName}ApprovalIntegrationHandler";

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Initializes a new instance of the <see cref=\"{className}\"/> class.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"approvalHandler\">The human approval handler.</param>");
        sb.AppendLine("    /// <param name=\"logger\">The logger.</param>");
        sb.AppendLine($"    public {className}(");
        sb.AppendLine("        IHumanApprovalHandler approvalHandler,");
        sb.AppendLine($"        ILogger<{className}> logger)");
        sb.AppendLine("    {");
        sb.AppendLine("        _approvalHandler = approvalHandler;");
        sb.AppendLine("        _logger = logger;");
        sb.AppendLine("    }");
    }

    private static void EmitApprovalHandler(StringBuilder sb, WorkflowModel model, ApprovalModel approval)
    {
        var eventName = $"Request{approval.ApprovalPointName}ApprovalEvent";
        var timeoutCommandName = $"{approval.ApprovalPointName}ApprovalTimeoutCommand";
        var setPendingCommandName = $"Set{approval.ApprovalPointName}PendingApprovalCommand";
        var resumeCommandName = $"Resume{approval.ApprovalPointName}ApprovalCommand";

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Handles the approval request event for {approval.ApprovalPointName}.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"evt\">The approval request event.</param>");
        sb.AppendLine("    /// <param name=\"context\">The message context.</param>");
        sb.AppendLine("    /// <param name=\"ct\">The cancellation token.</param>");
        sb.AppendLine("    /// <returns>The commands to execute.</returns>");
        sb.AppendLine($"    public async Task<object[]> HandleAsync(");
        sb.AppendLine($"        {eventName} evt,");
        sb.AppendLine("        IMessageContext context,");
        sb.AppendLine("        CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(evt, nameof(evt));");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(context, nameof(context));");
        sb.AppendLine();
        sb.AppendLine("        var requestId = $\"approval-{evt.WorkflowId:N}-{DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}\";");
        sb.AppendLine();
        sb.AppendLine("        var request = new ApprovalRequest");
        sb.AppendLine("        {");
        sb.AppendLine("            RequestId = requestId,");
        sb.AppendLine("            WorkflowId = evt.WorkflowId,");
        sb.AppendLine("            Type = ApprovalType.GeneralApproval,");
        sb.AppendLine("            Context = evt.Context,");
        sb.AppendLine("            Options = evt.Options?.ToList() ?? [],");
        sb.AppendLine("            Deadline = DateTimeOffset.UtcNow.Add(evt.Timeout)");
        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        var result = await _approvalHandler.RequestApprovalAsync(request, ct);");
        sb.AppendLine("        if (result.IsFailure)");
        sb.AppendLine("        {");
        sb.AppendLine($"            _logger.LogWarning(");
        sb.AppendLine($"                \"Approval request failed for {{ApprovalPointName}}: {{Error}}\",");
        sb.AppendLine($"                \"{approval.ApprovalPointName}\",");
        sb.AppendLine("                result.Error.Message);");
        sb.AppendLine();
        sb.AppendLine($"            return [new {resumeCommandName}(");
        sb.AppendLine("                evt.WorkflowId,");
        sb.AppendLine("                ApprovalDecision.Rejected,");
        sb.AppendLine("                null,");
        sb.AppendLine("                $\"Failed: {result.Error.Message}\")];");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        // Schedule timeout");
        sb.AppendLine($"        await context.ScheduleAsync(");
        sb.AppendLine($"            new {timeoutCommandName}(evt.WorkflowId, requestId),");
        sb.AppendLine("            evt.Timeout);");
        sb.AppendLine();
        sb.AppendLine($"        return [new {setPendingCommandName}(evt.WorkflowId, requestId)];");
        sb.AppendLine("    }");
    }

    private static void EmitClassFooter(StringBuilder sb)
    {
        sb.AppendLine("}");
    }
}
