// -----------------------------------------------------------------------
// <copyright file="ContextAssemblerEmitter.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System.Collections.Generic;
using System.Text;

using Strategos.Generators.Helpers;
using Strategos.Generators.Models;
using Strategos.Generators.Polyfills;

namespace Strategos.Generators.Emitters;

/// <summary>
/// Emits context assembler classes for workflow steps that have context configuration.
/// </summary>
/// <remarks>
/// Context assemblers implement <c>IContextAssembler{TState}</c> and are responsible
/// for assembling runtime context from multiple sources (state, RAG retrieval, literals).
/// </remarks>
internal static class ContextAssemblerEmitter
{
    /// <summary>
    /// Generates the context assembler source code for all steps with context in the workflow.
    /// </summary>
    /// <param name="model">The workflow model containing step information.</param>
    /// <returns>The generated C# source code for the context assembler classes.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="model"/> is null.</exception>
    public static string Emit(WorkflowModel model)
    {
        ThrowHelper.ThrowIfNull(model, nameof(model));

        var sb = new StringBuilder();

        // File header
        FileHeaderHelper.AppendAutoGeneratedHeader(sb);
        FileHeaderHelper.AppendUsings(
            sb,
            "System",
            "System.CodeDom.Compiler",
            "System.Collections.Generic",
            "System.Linq",
            "System.Threading",
            "System.Threading.Tasks",
            "Strategos.Agents.Models",
            "Strategos.Ontology.ObjectSets",
            "Strategos.Steps");

        // Namespace
        FileHeaderHelper.AppendNamespace(sb, model.Namespace);

        // Find steps with context and generate assemblers for each
        var stepsWithContext = GetStepsWithContext(model);
        var isFirst = true;

        foreach (var step in stepsWithContext)
        {
            if (!isFirst)
            {
                sb.AppendLine();
            }

            EmitContextAssembler(sb, model, step);
            isFirst = false;
        }

        return sb.ToString();
    }

    private static IReadOnlyList<StepModel> GetStepsWithContext(WorkflowModel model)
    {
        if (model.Steps is null)
        {
            return [];
        }

        var stepsWithContext = new List<StepModel>();
        foreach (var step in model.Steps)
        {
            if (step.Context is not null && step.Context.Sources.Count > 0)
            {
                stepsWithContext.Add(step);
            }
        }

        return stepsWithContext;
    }

    private static void EmitContextAssembler(StringBuilder sb, WorkflowModel model, StepModel step)
    {
        var stateType = model.StateTypeName ?? "object";
        var className = $"{step.StepName}ContextAssembler";

        // XML documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Assembles runtime context for the {step.StepName} step.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("[GeneratedCode(\"Strategos.Generators\", \"1.0.0\")]");
        sb.AppendLine($"public sealed partial class {className} : IContextAssembler<{stateType}>");
        sb.AppendLine("{");

        // Constructor with dependencies
        EmitConstructorAndDependencies(sb, step);

        // AssembleAsync method
        EmitAssembleAsyncMethod(sb, model, step);

        sb.AppendLine("}");
    }

    private static void EmitConstructorAndDependencies(StringBuilder sb, StepModel step)
    {
        // Check if any retrieval sources exist to determine if we need IObjectSetProvider
        var hasRetrievalSources = false;
        foreach (var source in step.Context!.Sources)
        {
            if (source is RetrievalContextSourceModel)
            {
                hasRetrievalSources = true;
                break;
            }
        }

        if (hasRetrievalSources)
        {
            // Single IObjectSetProvider field (shared across all retrieval sources)
            sb.AppendLine("    private readonly IObjectSetProvider _objectSetProvider;");

            sb.AppendLine();

            // Constructor
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Initializes a new instance of the <see cref=\"{step.StepName}ContextAssembler\"/> class.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public {step.StepName}ContextAssembler(IObjectSetProvider objectSetProvider)");
            sb.AppendLine("    {");
            sb.AppendLine("        ArgumentNullException.ThrowIfNull(objectSetProvider);");
            sb.AppendLine("        _objectSetProvider = objectSetProvider;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    private static void EmitAssembleAsyncMethod(StringBuilder sb, WorkflowModel model, StepModel step)
    {
        var stateType = model.StateTypeName ?? "object";

        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine($"    public async Task<AssembledContext> AssembleAsync({stateType} state, StepContext stepContext, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine("        var contextBuilder = new AssembledContextBuilder();");
        sb.AppendLine();

        var retrievalIndex = 0;
        foreach (var source in step.Context!.Sources)
        {
            switch (source)
            {
                case LiteralContextSourceModel literal:
                    EmitLiteralSource(sb, literal);
                    break;

                case StateContextSourceModel stateSource:
                    EmitStateSource(sb, stateSource);
                    break;

                case RetrievalContextSourceModel retrieval:
                    EmitRetrievalSource(sb, retrieval, retrievalIndex++);
                    break;
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return contextBuilder.Build();");
        sb.AppendLine("    }");
    }

    private static void EmitLiteralSource(StringBuilder sb, LiteralContextSourceModel literal)
    {
        // Escape the string for C# verbatim string
        var escapedValue = EscapeStringForCSharp(literal.Value);
        sb.AppendLine($"        // Literal context");
        sb.AppendLine($"        contextBuilder.AddLiteralContext(\"{escapedValue}\");");
    }

    private static void EmitStateSource(StringBuilder sb, StateContextSourceModel stateSource)
    {
        sb.AppendLine($"        // State context: {stateSource.PropertyPath}");
        sb.AppendLine($"        contextBuilder.AddStateContext(\"{stateSource.PropertyPath}\", {stateSource.AccessExpression});");
    }

    private static void EmitRetrievalSource(StringBuilder sb, RetrievalContextSourceModel retrieval, int retrievalIndex)
    {
        var resultsVarName = $"{ToCamelCase(retrieval.CollectionTypeName)}Results{retrievalIndex}";

        sb.AppendLine($"        // Retrieval context from {retrieval.CollectionTypeName}");

        // Build the query expression
        string queryExpr;
        if (retrieval.LiteralQuery is not null)
        {
            queryExpr = $"\"{EscapeStringForCSharp(retrieval.LiteralQuery)}\"";
        }
        else if (retrieval.QueryExpression is not null)
        {
            queryExpr = $"({retrieval.QueryExpression})(state)";
        }
        else
        {
            queryExpr = "string.Empty";
        }

        // Emit filters dictionary if filters exist
        var filtersVarName = $"{resultsVarName}Filters";
        if (retrieval.Filters.Count > 0)
        {
            sb.AppendLine($"        var {filtersVarName} = new Dictionary<string, object>");
            sb.AppendLine("        {");
            foreach (var filter in retrieval.Filters)
            {
                if (filter.IsStatic)
                {
                    sb.AppendLine($"            {{ \"{EscapeStringForCSharp(filter.Key)}\", \"{EscapeStringForCSharp(filter.StaticValue!)}\" }},");
                }
                else
                {
                    sb.AppendLine($"            {{ \"{EscapeStringForCSharp(filter.Key)}\", ({filter.ValueExpression})(state) }},");
                }
            }

            sb.AppendLine("        };");
        }

        // Build SimilarityExpression
        var minRelevanceLiteral = ((double)retrieval.MinRelevance).ToString(System.Globalization.CultureInfo.InvariantCulture);
        sb.AppendLine($"        var {resultsVarName}Expression = new SimilarityExpression(");
        sb.AppendLine($"            new RootExpression(typeof({retrieval.CollectionTypeName}), nameof({retrieval.CollectionTypeName})),");
        if (retrieval.Filters.Count > 0)
        {
            sb.AppendLine($"            {queryExpr}, {retrieval.TopK}, {minRelevanceLiteral},");
            sb.AppendLine($"            filters: {filtersVarName});");
        }
        else
        {
            sb.AppendLine($"            {queryExpr}, {retrieval.TopK}, {minRelevanceLiteral});");
        }

        sb.AppendLine($"        var {resultsVarName} = await _objectSetProvider.ExecuteSimilarityAsync<{retrieval.CollectionTypeName}>({resultsVarName}Expression, cancellationToken);");

        // Map to RetrievalResult list
        sb.AppendLine($"        var {resultsVarName}List = {resultsVarName}.Items.Select((item, i) => new RetrievalResult");
        sb.AppendLine("        {");
        sb.AppendLine("            Content = item.ToString(),");
        sb.AppendLine($"            Score = {resultsVarName}.Scores[i],");
        sb.AppendLine("        }).ToList();");
        sb.AppendLine($"        contextBuilder.AddRetrievalContext(\"{retrieval.CollectionTypeName}\", {resultsVarName}List);");
    }

    private static string ToCamelCase(string pascalCase)
    {
        if (string.IsNullOrEmpty(pascalCase))
        {
            return pascalCase;
        }

        return char.ToLowerInvariant(pascalCase[0]) + pascalCase.Substring(1);
    }

    private static string EscapeStringForCSharp(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}

