// -----------------------------------------------------------------------
// <copyright file="ExtensionsEmitter.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using System.Text;

using Strategos.Generators.Helpers;
using Strategos.Generators.Models;
using Strategos.Generators.Polyfills;

namespace Strategos.Generators.Emitters;

/// <summary>
/// Emits DI extension methods for workflow registration.
/// </summary>
internal static class ExtensionsEmitter
{
    /// <summary>
    /// Generates the DI extension method source code for the given workflow model.
    /// </summary>
    /// <param name="model">The workflow model containing registration information.</param>
    /// <returns>The generated C# source code for the extension method.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="model"/> is null.</exception>
    public static string Emit(WorkflowModel model)
    {
        ThrowHelper.ThrowIfNull(model, nameof(model));

        var sb = new StringBuilder();

        // File header
        FileHeaderHelper.AppendAutoGeneratedHeader(sb);

        // Collect usings including step namespaces
        var usings = new List<string>
        {
            "System",
            "Microsoft.Extensions.DependencyInjection",
        };

        // Event-sourced mode needs Marten for SnapshottedAggregation configuration.
        // Marten 9.x relocated SnapshotLifecycle into JasperFx.Events.Projections
        // (the shared JasperFx.Events event-store core), so that namespace is
        // required for the generated opts.Projections.Snapshot<T>(SnapshotLifecycle.Inline)
        // to resolve when the extensions are compiled against a real Marten reference.
        if (model.IsEventSourced)
        {
            usings.Add("Marten");
            usings.Add("Marten.Events.Aggregation");
            usings.Add("Marten.Events.Projections");
            usings.Add("JasperFx.Events.Projections");
        }

        // Add step type namespaces from the model
        if (model.Steps is not null)
        {
            foreach (var step in model.Steps)
            {
                var ns = GetNamespaceFromTypeName(step.StepTypeName);
                if (!string.IsNullOrEmpty(ns) && !usings.Contains(ns))
                {
                    usings.Add(ns);
                }
            }
        }

        FileHeaderHelper.AppendUsings(sb, usings.ToArray());

        // Namespace
        FileHeaderHelper.AppendNamespace(sb, model.Namespace);

        // Extension class
        EmitExtensionsClass(sb, model);

        return sb.ToString();
    }

    /// <summary>
    /// Extracts the namespace from a fully qualified type name.
    /// </summary>
    private static string GetNamespaceFromTypeName(string typeName)
    {
        var lastDot = typeName.LastIndexOf('.');
        return lastDot > 0 ? typeName.Substring(0, lastDot) : string.Empty;
    }

    /// <summary>
    /// Gets the unique step names from the model, using Steps collection if available, otherwise StepNames.
    /// </summary>
    private static IEnumerable<string> GetStepNames(WorkflowModel model)
    {
        if (model.Steps is not null)
        {
            return model.Steps.Select(s => s.StepName);
        }

        return model.StepNames;
    }

    private static void EmitExtensionsClass(StringBuilder sb, WorkflowModel model)
    {
        // XML documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// DI extension methods for the {model.WorkflowName} workflow.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static partial class {model.PascalName}WorkflowExtensions");
        sb.AppendLine("{");

        // Add method
        EmitAddMethod(sb, model);

        sb.AppendLine("}");
    }

    private static void EmitAddMethod(StringBuilder sb, WorkflowModel model)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Registers the {model.WorkflowName} workflow with the service collection.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to register with.</param>");
        sb.AppendLine("    /// <returns>The service collection for chaining.</returns>");
        sb.AppendLine($"    public static IServiceCollection Add{model.PascalName}Workflow(");
        sb.AppendLine("        this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(services, nameof(services));");
        sb.AppendLine();

        // Register unique step types (not phase names which may include loop prefixes)
        sb.AppendLine("        // Register step types");
        var registeredStepTypes = new HashSet<string>(StringComparer.Ordinal);
        var stepNames = GetStepNames(model);
        foreach (var stepName in stepNames)
        {
            if (registeredStepTypes.Add(stepName))
            {
                sb.AppendLine($"        services.AddTransient<{stepName}>();");
            }
        }

        // Register branch case step types
        if (model.Branches is not null)
        {
            foreach (var branch in model.Branches)
            {
                foreach (var branchCase in branch.Cases)
                {
                    foreach (var stepName in branchCase.StepNames)
                    {
                        if (registeredStepTypes.Add(stepName))
                        {
                            sb.AppendLine($"        services.AddTransient<{stepName}>();");
                        }
                    }
                }
            }
        }

        sb.AppendLine();

        // Register worker handlers (one per unique step type)
        sb.AppendLine("        // Register worker handlers");
        registeredStepTypes.Clear();
        foreach (var stepName in stepNames)
        {
            if (registeredStepTypes.Add(stepName))
            {
                sb.AppendLine($"        services.AddTransient<{stepName}Handler>();");
            }
        }

        // Register branch case step handlers
        if (model.Branches is not null)
        {
            foreach (var branch in model.Branches)
            {
                foreach (var branchCase in branch.Cases)
                {
                    foreach (var stepName in branchCase.StepNames)
                    {
                        if (registeredStepTypes.Add(stepName))
                        {
                            sb.AppendLine($"        services.AddTransient<{stepName}Handler>();");
                        }
                    }
                }
            }
        }

        // Register workflow-level OnFailure handler step worker handlers (#140 Task
        // 3.1). These are DISTINCT FailureHandler_{id}_{step}Handler classes (not the
        // folded main-flow {step}Handler), one per OnFailure step, so the saga's
        // ExecuteFailureHandler_{id}_{step}WorkerCommand has a resolvable receiver.
        if (model.FailureHandlers is not null)
        {
            foreach (var failureHandler in model.FailureHandlers)
            {
                var sanitizedId = failureHandler.HandlerId.Replace("-", "_");
                foreach (var stepName in failureHandler.StepNames)
                {
                    sb.AppendLine($"        services.AddTransient<FailureHandler_{sanitizedId}_{stepName}Handler>();");
                }
            }
        }

        // Register context assemblers (DR-6). One per step that declared
        // .WithContext(...); the step's worker handler takes it as a constructor
        // dependency. A retrieval-bearing assembler additionally depends on
        // IObjectSetProvider, which the ontology host registers separately.
        //
        // F3: the step-type + worker-handler registration above explicitly
        // enumerates branch (model.Branches) steps as a separate source, so the
        // assembler registration mirrors that source coverage to keep parity and
        // stay robust if a branch/failure-handler step ever lives ONLY in those
        // collections. The context flag lives on the StepModel (model.Steps), so we
        // first build a name -> has-context lookup, then register the assembler for
        // every context-bearing step reached through ANY source. The shared
        // registeredAssemblers set guarantees each assembler is registered exactly
        // once (no duplicate AddTransient), so this is idempotent: a step already
        // covered by the model.Steps pass is never re-registered from the branch /
        // failure-handler pass.
        if (model.Steps is not null)
        {
            var stepsWithContext = new HashSet<string>(StringComparer.Ordinal);
            foreach (var step in model.Steps)
            {
                if (step.Context is not null && step.Context.Sources.Count > 0)
                {
                    stepsWithContext.Add(step.StepName);
                }
            }

            var registeredAssemblers = new HashSet<string>(StringComparer.Ordinal);
            var emittedHeader = false;

            void RegisterAssembler(string stepName)
            {
                if (!stepsWithContext.Contains(stepName))
                {
                    return;
                }

                if (!registeredAssemblers.Add(stepName))
                {
                    return;
                }

                if (!emittedHeader)
                {
                    sb.AppendLine();
                    sb.AppendLine("        // Register context assemblers");
                    emittedHeader = true;
                }

                sb.AppendLine($"        services.AddTransient<{stepName}ContextAssembler>();");
            }

            // Primary source: every lowered step model (main flow, branch,
            // failure-handler, low-confidence, compensation steps are all folded in).
            foreach (var step in model.Steps)
            {
                RegisterAssembler(step.StepName);
            }

            // Mirror the step-type/worker registration sources so the assembler
            // registration can never silently drop a context-bearing branch or
            // failure-handler step (idempotent via registeredAssemblers).
            if (model.Branches is not null)
            {
                foreach (var branch in model.Branches)
                {
                    foreach (var branchCase in branch.Cases)
                    {
                        foreach (var stepName in branchCase.StepNames)
                        {
                            RegisterAssembler(stepName);
                        }
                    }
                }
            }

            if (model.FailureHandlers is not null)
            {
                foreach (var handler in model.FailureHandlers)
                {
                    foreach (var stepName in handler.StepNames)
                    {
                        RegisterAssembler(stepName);
                    }
                }
            }
        }

        sb.AppendLine();

        // Force evaluation of workflow definition to register loop conditions
        // The Definition property triggers the fluent DSL builder chain which
        // registers conditions in WorkflowConditionRegistry for runtime lookup
        sb.AppendLine("        // Force evaluation of workflow definition to register loop conditions");
        sb.AppendLine($"        _ = {model.PascalName}WorkflowDefinition.Definition;");

        // Configure Marten SnapshottedAggregation for event-sourced workflows
        if (model.IsEventSourced && !string.IsNullOrEmpty(model.StateTypeName))
        {
            sb.AppendLine();
            sb.AppendLine("        // Configure Marten event-sourced aggregate with snapshotting");
            sb.AppendLine($"        services.ConfigureMarten(opts =>");
            sb.AppendLine("        {");
            sb.AppendLine($"            opts.Projections.Snapshot<{model.StateTypeName}>(SnapshotLifecycle.Inline);");
            sb.AppendLine("        });");
        }

        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }
}
