// -----------------------------------------------------------------------
// <copyright file="SagaEmitter.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System.Collections.Generic;
using System.Text;

using Strategos.Generators.Emitters.Saga;
using Strategos.Generators.Helpers;
using Strategos.Generators.Models;
using Strategos.Generators.Polyfills;

namespace Strategos.Generators.Emitters;

/// <summary>
/// Orchestrates the emission of a Wolverine saga class for a workflow.
/// </summary>
/// <remarks>
/// <para>
/// This class serves as a thin orchestrator that composes multiple component emitters
/// to generate the complete saga source code. Each component emitter implements
/// <see cref="ISagaComponentEmitter"/> and handles a specific section of the saga.
/// </para>
/// <para>
/// The components are emitted in the following order:
/// <list type="number">
///   <item><description>Properties (WorkflowId, State, Phase, loop counters)</description></item>
///   <item><description>Concurrency error policy (static Configure(HandlerChain))</description></item>
///   <item><description>Loop condition methods (ShouldExitXxxLoop)</description></item>
///   <item><description>Start method (static factory)</description></item>
///   <item><description>Step handlers (start and completed for each step)</description></item>
///   <item><description>Approval handlers (resume handlers for approval checkpoints)</description></item>
///   <item><description>NotFound handlers (for saga not found scenarios)</description></item>
/// </list>
/// </para>
/// </remarks>
internal static class SagaEmitter
{
    /// <summary>
    /// The ordered list of component emitters that generate saga sections.
    /// </summary>
    private static readonly IReadOnlyList<ISagaComponentEmitter> ComponentEmitters =
    [
        new SagaPropertiesEmitter(),
        new SagaConcurrencyPolicyEmitter(),
        new SagaLoopConditionsEmitter(),
        new SagaStartMethodEmitter(),
        new SagaStepHandlersEmitter(),
        new SagaTimeoutComponentEmitter(),
        new SagaApprovalComponentEmitter(),
        new SagaFailureHandlerComponentEmitter(),
        new SagaCompensationComponentEmitter(),
        new SagaNotFoundHandlersEmitter(),
    ];

    /// <summary>
    /// Generates the saga class source code for the given workflow model.
    /// </summary>
    /// <param name="model">The workflow model containing workflow information.</param>
    /// <returns>The generated C# source code for the saga class.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="model"/> is null.</exception>
    public static string Emit(WorkflowModel model)
    {
        ThrowHelper.ThrowIfNull(model, nameof(model));

        var sb = new StringBuilder();

        // File header
        FileHeaderHelper.AppendAutoGeneratedHeader(sb);

        // Collect usings
        var usings = new List<string>
        {
            "System",
            "System.Collections.Generic",
            "Strategos.Identity.Abstractions",
            "Strategos.Services",
            "Microsoft.Extensions.Logging",
            "Wolverine",

            // The saga-level concurrency error policy: HandlerChain lives in
            // Wolverine.Runtime.Handlers, the fluent OnException<T>()/RetryTimes()
            // surface lives in Wolverine.ErrorHandling.
            "Wolverine.ErrorHandling",
            "Wolverine.Persistence.Sagas",
            "Wolverine.Runtime.Handlers",
        };

        if (CompensationTopology.UsesDerivedRuntime(model))
        {
            usings.Add("System.Linq");
        }

        // Event-sourced mode needs IDocumentSession from Marten
        if (model.IsEventSourced)
        {
            usings.Add("Marten");
        }

        // Add step type namespaces from the model
        if (model.Steps is not null)
        {
            foreach (var step in model.Steps)
            {
                var ns = GetNamespaceFromTypeName(step.StepTypeName);
                if (!string.IsNullOrEmpty(ns) && !usings.Contains(ns))
                {
                    usings.Add(ns);
                }
            }
        }

        FileHeaderHelper.AppendUsings(sb, usings.ToArray());

        // Namespace
        FileHeaderHelper.AppendNamespace(sb, model.Namespace);

        // Class declaration
        EmitClassDeclaration(sb, model);

        // Delegate to all component emitters uniformly
        foreach (var emitter in ComponentEmitters)
        {
            emitter.Emit(sb, model);
        }

        // Close class
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Gets the saga class name for a workflow model.
    /// </summary>
    /// <param name="model">The workflow model.</param>
    /// <returns>The saga class name with optional version suffix.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="model"/> is null.</exception>
    public static string GetSagaClassName(WorkflowModel model)
    {
        ThrowHelper.ThrowIfNull(model, nameof(model));

        return NamingHelper.GetSagaClassName(model.PascalName, model.Version);
    }

    /// <summary>
    /// Extracts the namespace from a fully qualified type name.
    /// </summary>
    private static string GetNamespaceFromTypeName(string typeName)
    {
        var lastDot = typeName.LastIndexOf('.');
        return lastDot > 0 ? typeName.Substring(0, lastDot) : string.Empty;
    }

    /// <summary>
    /// Emits the class declaration with XML documentation and attributes.
    /// </summary>
    /// <param name="sb">The StringBuilder to append to.</param>
    /// <param name="model">The workflow model.</param>
    private static void EmitClassDeclaration(StringBuilder sb, WorkflowModel model)
    {
        var sagaClassName = GetSagaClassName(model);

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Wolverine saga for the {model.WorkflowName} workflow.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("/// Implements <c>JasperFx.IRevisioned</c> over the inherited <c>Saga.Version</c>");
        sb.AppendLine("/// (int). Wolverine's MartenPersistenceFrameProvider.DetermineUpdateFrame tests the");
        sb.AppendLine("/// saga type for that interface and only then emits");
        sb.AppendLine("/// <c>documentSession.UpdateRevision(saga, expectedSagaRevision)</c>; without it the");
        sb.AppendLine("/// emitted persistence call is a plain <c>Update</c>, which leaves Marten's numeric");
        sb.AppendLine("/// revision guard at 0 and makes concurrent saga transitions last-write-wins.");
        sb.AppendLine("/// </remarks>");

        // Fully qualified: `using JasperFx;` would drag the whole JasperFx root
        // namespace into every generated saga file and risk colliding with
        // consumer types (the same CS0616-class hazard that forces
        // [JasperFx.Identity] to be written out in full).
        sb.AppendLine($"public partial class {sagaClassName} : Saga, IPhaseAwareSaga, JasperFx.IRevisioned");
        sb.AppendLine("{");
    }
}
