// -----------------------------------------------------------------------
// <copyright file="TransitionsEmitter.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System.Text;

using Strategos.Generators.Helpers;
using Strategos.Generators.Models;
using Strategos.Generators.Polyfills;

namespace Strategos.Generators.Emitters;

/// <summary>
/// Emits the transition table class for a workflow.
/// </summary>
/// <remarks>
/// The emitted <c>ValidTransitions</c> / <c>IsValidTransition</c> pair is public generated API,
/// so it describes the workflow's actual phase graph — fork dispatch and join, branch dispatch,
/// case rejoin and case termination, loop continue and exit, and handler chains — rather than a
/// flat chain over the step-name list. A workflow's step-name list is not the main flow: several
/// lowering blocks append names to it, and chaining consecutive entries publishes edges between
/// exclusive sibling paths that no execution ever takes.
/// </remarks>
internal static class TransitionsEmitter
{
    /// <summary>
    /// Generates the transition table source code for the given workflow model.
    /// </summary>
    /// <param name="model">The workflow model containing transition information.</param>
    /// <returns>The generated C# source code for the transition table.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="model"/> is null.</exception>
    public static string Emit(WorkflowModel model)
    {
        ThrowHelper.ThrowIfNull(model, nameof(model));

        var sb = new StringBuilder();

        // File header
        FileHeaderHelper.AppendAutoGeneratedHeader(sb);
        FileHeaderHelper.AppendUsings(sb, "System", "System.Collections.Generic");

        // Namespace
        FileHeaderHelper.AppendNamespace(sb, model.Namespace);

        // Transitions class
        EmitTransitionsClass(sb, model);

        return sb.ToString();
    }

    private static void EmitTransitionsClass(StringBuilder sb, WorkflowModel model)
    {
        var phaseEnumName = model.PhaseEnumName;
        var graph = PhaseGraph.Build(model);

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Valid state transitions for the {model.WorkflowName} workflow.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static partial class {model.PascalName}Transitions");
        sb.AppendLine("{");

        // ValidTransitions dictionary
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Dictionary mapping each phase to its valid successor phases.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static readonly IReadOnlyDictionary<{phaseEnumName}, {phaseEnumName}[]> ValidTransitions =");
        sb.AppendLine($"        new Dictionary<{phaseEnumName}, {phaseEnumName}[]>");
        sb.AppendLine("        {");

        // NotStarted enters the workflow at its first MAIN-FLOW step. An appended
        // off-main-flow entry is reached through its own construct, never from the start.
        sb.AppendLine($"            {{ {phaseEnumName}.NotStarted, [{phaseEnumName}.{graph.EntryPhaseName}] }},");

        foreach (var stepName in model.StepNames)
        {
            var targets = graph.SuccessorsOf(stepName);
            var rendered = string.Join(", ", targets.Select(t => $"{phaseEnumName}.{t}"));
            sb.AppendLine($"            {{ {phaseEnumName}.{stepName}, [{rendered}] }},");
        }

        // Terminal phases have no transitions
        sb.AppendLine($"            {{ {phaseEnumName}.{PhaseGraph.CompletedPhase}, [] }},");
        sb.AppendLine($"            {{ {phaseEnumName}.{PhaseGraph.FailedPhase}, [] }},");

        sb.AppendLine("        };");
        sb.AppendLine();

        // IsValidTransition helper method
        EmitIsValidTransitionMethod(sb, model);

        sb.AppendLine("}");
    }

    private static void EmitIsValidTransitionMethod(StringBuilder sb, WorkflowModel model)
    {
        var phaseEnumName = model.PhaseEnumName;

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Checks if a transition from one phase to another is valid.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"from\">The current phase.</param>");
        sb.AppendLine($"    /// <param name=\"to\">The target phase.</param>");
        sb.AppendLine("    /// <returns>True if the transition is valid; otherwise, false.</returns>");
        sb.AppendLine($"    public static bool IsValidTransition({phaseEnumName} from, {phaseEnumName} to)");
        sb.AppendLine("    {");
        sb.AppendLine("        return ValidTransitions.TryGetValue(from, out var validTargets)");
        sb.AppendLine("            && Array.IndexOf(validTargets, to) >= 0;");
        sb.AppendLine("    }");
    }
}
