// -----------------------------------------------------------------------
// <copyright file="TransitionsEmitter.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System.Text;

using Strategos.Generators.Helpers;
using Strategos.Generators.Models;
using Strategos.Generators.Polyfills;

namespace Strategos.Generators.Emitters;

/// <summary>
/// Emits the transition table class for a workflow.
/// </summary>
internal static class TransitionsEmitter
{
    /// <summary>
    /// Generates the transition table source code for the given workflow model.
    /// </summary>
    /// <param name="model">The workflow model containing transition information.</param>
    /// <returns>The generated C# source code for the transition table.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="model"/> is null.</exception>
    public static string Emit(WorkflowModel model)
    {
        ThrowHelper.ThrowIfNull(model, nameof(model));

        var sb = new StringBuilder();

        // File header
        FileHeaderHelper.AppendAutoGeneratedHeader(sb);
        FileHeaderHelper.AppendUsings(sb, "System", "System.Collections.Generic");

        // Namespace
        FileHeaderHelper.AppendNamespace(sb, model.Namespace);

        // Transitions class
        EmitTransitionsClass(sb, model);

        return sb.ToString();
    }

    private static void EmitTransitionsClass(StringBuilder sb, WorkflowModel model)
    {
        var phaseEnumName = model.PhaseEnumName;

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Valid state transitions for the {model.WorkflowName} workflow.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static partial class {model.PascalName}Transitions");
        sb.AppendLine("{");

        // ValidTransitions dictionary
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Dictionary mapping each phase to its valid successor phases.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static readonly IReadOnlyDictionary<{phaseEnumName}, {phaseEnumName}[]> ValidTransitions =");
        sb.AppendLine($"        new Dictionary<{phaseEnumName}, {phaseEnumName}[]>");
        sb.AppendLine("        {");

        // NotStarted -> First step (or Completed if no steps)
        var firstStep = model.StepNames.Count > 0 ? model.StepNames[0] : "Completed";
        sb.AppendLine($"            {{ {phaseEnumName}.NotStarted, [{phaseEnumName}.{firstStep}] }},");

        // Each step transitions to the next step (or Completed for last step)
        for (var i = 0; i < model.StepNames.Count; i++)
        {
            var currentStep = model.StepNames[i];
            var nextPhase = i < model.StepNames.Count - 1
                ? model.StepNames[i + 1]
                : "Completed";

            // Steps can transition to next step or Failed
            sb.AppendLine($"            {{ {phaseEnumName}.{currentStep}, [{phaseEnumName}.{nextPhase}, {phaseEnumName}.Failed] }},");
        }

        // Terminal phases have no transitions
        sb.AppendLine($"            {{ {phaseEnumName}.Completed, [] }},");
        sb.AppendLine($"            {{ {phaseEnumName}.Failed, [] }},");

        sb.AppendLine("        };");
        sb.AppendLine();

        // IsValidTransition helper method
        EmitIsValidTransitionMethod(sb, model);

        sb.AppendLine("}");
    }

    private static void EmitIsValidTransitionMethod(StringBuilder sb, WorkflowModel model)
    {
        var phaseEnumName = model.PhaseEnumName;

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Checks if a transition from one phase to another is valid.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"from\">The current phase.</param>");
        sb.AppendLine($"    /// <param name=\"to\">The target phase.</param>");
        sb.AppendLine("    /// <returns>True if the transition is valid; otherwise, false.</returns>");
        sb.AppendLine($"    public static bool IsValidTransition({phaseEnumName} from, {phaseEnumName} to)");
        sb.AppendLine("    {");
        sb.AppendLine("        return ValidTransitions.TryGetValue(from, out var validTargets)");
        sb.AppendLine("            && Array.IndexOf(validTargets, to) >= 0;");
        sb.AppendLine("    }");
    }
}
