// -----------------------------------------------------------------------
// <copyright file="WorkerHandlerEmitter.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System.Collections.Generic;
using System.Text;

using Strategos.Generators.Helpers;
using Strategos.Generators.Models;
using Strategos.Generators.Polyfills;

namespace Strategos.Generators.Emitters;

/// <summary>
/// Emits Wolverine worker handler classes for workflow steps.
/// </summary>
/// <remarks>
/// Implements the "Muscle" part of the Brain &amp; Muscle pattern:
/// Workers execute steps (LLM calls, I/O) without holding saga database locks.
/// </remarks>
internal static class WorkerHandlerEmitter
{
    /// <summary>
    /// Generates the worker handler classes source code for the given workflow model.
    /// </summary>
    /// <param name="model">The workflow model containing step information.</param>
    /// <returns>The generated C# source code for the worker handler classes.</returns>
    /// <exception cref="ArgumentNullException">Thrown when <paramref name="model"/> is null.</exception>
    public static string Emit(WorkflowModel model)
    {
        ThrowHelper.ThrowIfNull(model, nameof(model));

        var sb = new StringBuilder();

        // File header
        FileHeaderHelper.AppendAutoGeneratedHeader(sb);

        // Collect unique step namespaces for usings
        var usings = new List<string>
        {
            "System",
            "System.CodeDom.Compiler",
            "System.Diagnostics",
            "System.Threading",
            "System.Threading.Tasks",
            "Strategos.Steps",
            "Strategos.Agents.Telemetry",
            "Microsoft.Extensions.Logging",
        };

        // Wolverine per-handler error policy (DR-2 retry, DR-3 compensation): only
        // pulled in when at least one step lowers a retry OR a compensation onto its
        // handler chain, so a workflow with no resilience keeps its handler file
        // byte-identical to the prior baseline. HandlerChain and InvokeResult live in
        // Wolverine.Runtime.Handlers; the fluent OnAnyException()/RetryTimes()/
        // RetryWithCooldown()/WithExponentialJitter()/CompensatingAction() extensions
        // live in Wolverine.ErrorHandling.
        // Also pulled in when the workflow declares an OnFailure chain: every
        // main-flow step then lowers a trigger-publishing Configure(HandlerChain) so
        // a thrown step routes into the OnFailure recovery chain (#140 Task 3.1).
        if ((model.Steps is not null && model.Steps.Any(s => s.Retry is not null || s.Compensation is not null))
            || model.HasFailureHandlers)
        {
            usings.Add("Wolverine.ErrorHandling");
            usings.Add("Wolverine.Runtime.Handlers");
        }

        // Context assembler wiring (DR-6): only pulled in when at least one step
        // declared .WithContext(...). IContextAwareStep is the opt-in delivery
        // contract a step implements to receive AssembledContext; both live in
        // Strategos.Agents. Guarded so a context-free workflow keeps its prior
        // handler file unchanged.
        if (model.Steps is not null && model.Steps.Any(s => s.Context is not null && s.Context.Sources.Count > 0))
        {
            usings.Add("Strategos.Agents.Abstractions");
            usings.Add("Strategos.Agents.Models");
        }

        // Add step type namespaces from the model
        if (model.Steps is not null)
        {
            foreach (var step in model.Steps)
            {
                var ns = GetNamespaceFromTypeName(step.StepTypeName);
                if (!string.IsNullOrEmpty(ns) && !usings.Contains(ns))
                {
                    usings.Add(ns);
                }
            }
        }

        FileHeaderHelper.AppendUsings(sb, usings.ToArray());

        // Namespace
        FileHeaderHelper.AppendNamespace(sb, model.Namespace);
        sb.AppendLine();

        // Generate a handler class for each unique step type (not phase)
        // The same step type can appear in multiple phases (main flow + loop), but we only need one handler
        var emittedStepNames = new HashSet<string>(StringComparer.Ordinal);
        if (model.Steps is not null)
        {
            foreach (var step in model.Steps)
            {
                if (emittedStepNames.Add(step.StepName))
                {
                    EmitHandlerClass(sb, model, step);
                    sb.AppendLine();
                }
            }
        }
        else
        {
            // Fallback for models without Step collection - use StepNames directly
            foreach (var stepName in model.StepNames)
            {
                if (emittedStepNames.Add(stepName))
                {
                    EmitHandlerClassFromName(sb, model, stepName);
                    sb.AppendLine();
                }
            }
        }

        // Generate handler classes for branch case steps
        // These steps execute conditionally based on discriminator
        if (model.Branches is not null)
        {
            foreach (var branch in model.Branches)
            {
                foreach (var branchCase in branch.Cases)
                {
                    foreach (var stepName in branchCase.StepNames)
                    {
                        if (emittedStepNames.Add(stepName))
                        {
                            EmitHandlerClassFromName(sb, model, stepName);
                            sb.AppendLine();
                        }
                    }
                }
            }
        }

        // Generate worker handlers for workflow-level OnFailure handler steps (#140
        // Task 3.1). The saga dispatches a dedicated
        // ExecuteFailureHandler_{id}_{step}WorkerCommand for each OnFailure step and
        // expects a FailureHandler_{id}_{step}Completed event back; without this
        // handler the dispatched command had no receiver and the OnFailure chain was
        // dead. The handler is a DISTINCT class
        // (FailureHandler_{id}_{step}Handler) so it never collides with the folded
        // main-flow {step}Handler when the failure step type is also a main-flow step.
        if (model.FailureHandlers is not null)
        {
            foreach (var handler in model.FailureHandlers)
            {
                var sanitizedId = handler.HandlerId.Replace("-", "_");
                foreach (var stepName in handler.StepNames)
                {
                    EmitFailureHandlerWorkerClass(sb, model, stepName, sanitizedId);
                    sb.AppendLine();
                }
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emits the worker handler class for a single workflow-level OnFailure handler
    /// step (#140 Task 3.1). The handler receives the saga-dispatched
    /// <c>ExecuteFailureHandler_{id}_{step}WorkerCommand</c>, executes the OnFailure
    /// step (the "Muscle"), and returns the
    /// <c>FailureHandler_{id}_{step}Completed</c> event the saga folds and routes on.
    /// </summary>
    private static void EmitFailureHandlerWorkerClass(
        StringBuilder sb,
        WorkflowModel model,
        string stepName,
        string sanitizedId)
    {
        var workerCommandName = $"ExecuteFailureHandler_{sanitizedId}_{stepName}WorkerCommand";
        var completedEventName = $"FailureHandler_{sanitizedId}_{stepName}Completed";
        var handlerClassName = $"FailureHandler_{sanitizedId}_{stepName}Handler";

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Worker handler for the {stepName} workflow-level OnFailure handler step.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("/// <para>");
        sb.AppendLine("/// This handler implements the \"Muscle\" part of the Brain &amp; Muscle pattern for");
        sb.AppendLine("/// the workflow's OnFailure recovery chain. It executes the failure-handler step");
        sb.AppendLine("/// after a workflow step failed, then returns the completed event the saga folds");
        sb.AppendLine("/// into state and routes on (chaining to the next OnFailure step or marking the");
        sb.AppendLine("/// workflow Failed).");
        sb.AppendLine("/// </para>");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine("[GeneratedCode(\"Strategos.Generators\", \"1.0.0\")]");
        sb.AppendLine($"public sealed partial class {handlerClassName}(");
        sb.AppendLine($"    {stepName} step,");
        sb.AppendLine($"    ILogger<{handlerClassName}> logger)");
        sb.AppendLine("{");
        sb.AppendLine($"    private readonly {stepName} _step = step;");
        sb.AppendLine($"    private readonly ILogger<{handlerClassName}> _logger = logger;");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Handles the {workerCommandName} by executing the failure-handler step.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"command\">The worker command with workflow state and failure context.</param>");
        sb.AppendLine("    /// <param name=\"ct\">The cancellation token.</param>");
        sb.AppendLine("    /// <returns>The completion event for saga routing via cascading.</returns>");
        sb.AppendLine("    /// <exception cref=\"ArgumentNullException\">Thrown when <paramref name=\"command\"/> is null.</exception>");
        sb.AppendLine($"    public async Task<{completedEventName}> Handle(");
        sb.AppendLine($"        {workerCommandName} command,");
        sb.AppendLine("        CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(command, nameof(command));");
        sb.AppendLine();
        sb.AppendLine("        _logger.LogDebug(");
        sb.AppendLine("            \"Executing failure handler step {StepName} for workflow {WorkflowId}\",");
        sb.AppendLine($"            \"{stepName}\",");
        sb.AppendLine("            command.WorkflowId);");
        sb.AppendLine();
        sb.AppendLine($"        using var activity = WorkflowTelemetry.StartStepSpan(\"{stepName}\", command.WorkflowId);");
        sb.AppendLine("        var sw = Stopwatch.StartNew();");
        sb.AppendLine();
        sb.AppendLine($"        var stepContext = StepContext.Create(command.WorkflowId, \"{stepName}\", \"{stepName}\");");
        sb.AppendLine("        var result = await _step.ExecuteAsync(command.State, stepContext, ct);");
        sb.AppendLine();
        sb.AppendLine("        sw.Stop();");
        sb.AppendLine("        activity?.SetStatus(ActivityStatusCode.Ok);");
        sb.AppendLine("        activity?.SetTag(\"step.duration_ms\", sw.ElapsedMilliseconds);");
        sb.AppendLine();
        sb.AppendLine("        _logger.LogDebug(");
        sb.AppendLine("            \"Failure handler step {StepName} completed for workflow {WorkflowId} in {ElapsedMs}ms\",");
        sb.AppendLine($"            \"{stepName}\",");
        sb.AppendLine("            command.WorkflowId,");
        sb.AppendLine("            sw.ElapsedMilliseconds);");
        sb.AppendLine();
        sb.AppendLine("        // Return cascading: Wolverine routes via [SagaIdentity] on the event");
        sb.AppendLine($"        return new {completedEventName}(");
        sb.AppendLine("            command.WorkflowId,");
        sb.AppendLine("            command.StepExecutionId,");
        sb.AppendLine("            result.UpdatedState,");
        sb.AppendLine("            DateTimeOffset.UtcNow);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    /// <summary>
    /// Extracts the namespace from a fully qualified type name.
    /// </summary>
    private static string GetNamespaceFromTypeName(string typeName)
    {
        var lastDot = typeName.LastIndexOf('.');
        return lastDot > 0 ? typeName.Substring(0, lastDot) : string.Empty;
    }

    private static void EmitHandlerClass(StringBuilder sb, WorkflowModel model, StepModel step)
    {
        EmitHandlerClassCore(sb, model, step.StepName, step);
    }

    private static void EmitHandlerClassFromName(StringBuilder sb, WorkflowModel model, string stepName)
    {
        EmitHandlerClassCore(sb, model, stepName, step: null);
    }

    /// <summary>
    /// Builds the set of step names that belong to a workflow-level OnFailure
    /// recovery chain. These steps must NOT publish the failure-handler trigger
    /// themselves (they ARE the recovery path); only main-flow steps route into the
    /// OnFailure chain on failure.
    /// </summary>
    private static HashSet<string> BuildFailureHandlerStepNames(WorkflowModel model)
    {
        var set = new HashSet<string>(StringComparer.Ordinal);
        if (model.FailureHandlers is null)
        {
            return set;
        }

        foreach (var handler in model.FailureHandlers)
        {
            foreach (var stepName in handler.StepNames)
            {
                set.Add(stepName);
            }
        }

        return set;
    }

    private static void EmitHandlerClassCore(StringBuilder sb, WorkflowModel model, string stepName, StepModel? step)
    {
        var workerCommandName = $"Execute{stepName}WorkerCommand";
        var completedEventName = $"{stepName}Completed";
        var handlerClassName = $"{stepName}Handler";
        var stateType = model.StateTypeName ?? "object";

        // A step that declared .WithContext(...) gets its generated
        // {Step}ContextAssembler injected and invoked before execution (DR-6).
        var hasContext = step is not null
            && step.Context is not null
            && step.Context.Sources.Count > 0;
        var assemblerTypeName = $"{stepName}ContextAssembler";

        // XML documentation
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Worker handler for the {stepName} step.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("/// <para>");
        sb.AppendLine("/// This handler implements the \"Muscle\" part of the Brain &amp; Muscle pattern.");
        sb.AppendLine("/// It executes step logic (LLM calls, I/O operations) without holding saga database locks,");
        sb.AppendLine("/// enabling better throughput and avoiding lock contention in high-volume scenarios.");
        sb.AppendLine("/// </para>");
        sb.AppendLine("/// <para>");
        sb.AppendLine("/// The handler wraps step execution with OpenTelemetry tracing and structured logging");
        sb.AppendLine("/// for production observability. Exceptions are logged with full context before re-throwing");
        sb.AppendLine("/// to allow Wolverine's retry policies to handle transient failures.");
        sb.AppendLine("/// </para>");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine("[GeneratedCode(\"Strategos.Generators\", \"1.0.0\")]");
        sb.AppendLine($"public sealed partial class {handlerClassName}(");
        sb.AppendLine($"    {stepName} step,");
        if (hasContext)
        {
            // The assembler is registered in DI (see ExtensionsEmitter) so
            // Wolverine can resolve it for this handler's primary constructor.
            sb.AppendLine($"    {assemblerTypeName} contextAssembler,");
        }

        sb.AppendLine($"    ILogger<{handlerClassName}> logger)");
        sb.AppendLine("{");

        // Private fields from primary constructor
        sb.AppendLine($"    private readonly {stepName} _step = step;");
        if (hasContext)
        {
            sb.AppendLine($"    private readonly {assemblerTypeName} _contextAssembler = contextAssembler;");
        }

        sb.AppendLine($"    private readonly ILogger<{handlerClassName}> _logger = logger;");
        sb.AppendLine();

        // Handle method
        EmitHandleMethod(sb, model, stepName, workerCommandName, completedEventName, stateType, hasContext);

        // A main-flow step routes into the workflow-level OnFailure chain when it
        // fails (#140 Task 3.1): its error chain must publish the
        // Trigger{Pascal}FailureHandlerCommand so the saga starts the OnFailure
        // chain. This is the previously-missing publish for a NON-compensated failing
        // step (compensation already publishes the same trigger via its own path).
        // The failure-handler steps themselves are excluded — they ARE the recovery
        // path and must not re-trigger it.
        var publishOnFailureTrigger =
            model.HasFailureHandlers
            && !BuildFailureHandlerStepNames(model).Contains(stepName)
            && (step is null || step.Compensation is null);

        // Per-handler Wolverine error policy (DR-2 retry, DR-3 compensation, plus the
        // OnFailure trigger publish above). Emitted when the step declared resilience
        // that lowers onto the handler's chain (retry and/or compensation) OR when a
        // main-flow step must publish the OnFailure trigger on failure. The re-throw
        // in the Handle catch block is what feeds this policy. Guarded so a step with
        // no resilience and no OnFailure routing keeps the no-policy baseline shape.
        if ((step is not null && (step.Retry is not null || step.Compensation is not null))
            || publishOnFailureTrigger)
        {
            sb.AppendLine();
            EmitConfigureMethod(sb, model, step, stepName, workerCommandName, publishOnFailureTrigger);
        }

        sb.AppendLine("}");
    }

    /// <summary>
    /// Emits a static <c>Configure(HandlerChain)</c> method that lowers the
    /// step's <see cref="RetryModel"/> and/or <see cref="CompensationModel"/> onto
    /// the handler's Wolverine chain as an <c>OnAnyException</c> error policy.
    /// Wolverine discovers this method by convention at codegen time and scopes the
    /// policy to this one handler.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The chain composes additively: a retry prefix
    /// (<c>RetryTimes</c>/<c>RetryWithCooldown</c>) is followed, when the step also
    /// declares <c>.Compensate&lt;T&gt;()</c> OR the workflow declares an
    /// <c>OnFailure</c> chain, by
    /// <c>.Then.CompensatingAction&lt;{WorkerCommand}&gt;(...)</c> that PUBLISHES the
    /// trigger failure-handler command on terminal failure (after retries are
    /// exhausted), with <c>InvokeResult.Stop</c> so the message is not retried again.
    /// This is what makes the previously-never-published trigger command reach the
    /// saga at runtime, so the compensation step (DR-3) and/or the workflow-level
    /// OnFailure chain (#140 Task 3.1) actually runs.
    /// </para>
    /// <para>
    /// When only compensation (or only OnFailure routing) is declared with no retry,
    /// the compensating action applies directly to <c>chain.OnAnyException()</c> with
    /// no retry prefix.
    /// </para>
    /// </remarks>
    private static void EmitConfigureMethod(
        StringBuilder sb,
        WorkflowModel model,
        StepModel? step,
        string stepName,
        string workerCommandName,
        bool publishOnFailureTrigger)
    {
        var retry = step?.Retry;
        var compensation = step?.Compensation;

        // The trigger is published on terminal failure when the step compensates OR
        // when this main-flow step must route into the workflow-level OnFailure chain.
        var publishesTrigger = compensation is not null || publishOnFailureTrigger;

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Configures this handler's Wolverine error policy. Lowered from the");
        sb.AppendLine("    /// step's <c>.WithRetry(...)</c> / <c>.Compensate&lt;T&gt;()</c> declaration");
        sb.AppendLine("    /// and/or the workflow's <c>OnFailure</c> chain; Wolverine discovers this");
        sb.AppendLine("    /// static method by convention and scopes the policy to this handler.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"chain\">The handler chain to apply the error policy to.</param>");
        sb.AppendLine("    public static void Configure(HandlerChain chain)");
        sb.AppendLine("    {");

        // Open the error chain. The retry prefix (if any) is emitted WITHOUT a
        // terminating ';' so a compensating action can be chained after it.
        sb.Append("        chain.OnAnyException()");

        if (retry is not null)
        {
            if (retry.InitialDelay is { } initialDelay)
            {
                // A configured delay lowers to a per-attempt cooldown schedule.
                var cooldowns = BuildCooldownSchedule(retry, initialDelay);
                sb.AppendLine();
                sb.Append($"            .RetryWithCooldown({cooldowns})");

                if (retry.UseJitter)
                {
                    sb.AppendLine();
                    sb.Append("            .WithExponentialJitter()");
                }
            }
            else
            {
                // No delay configured: a simple fixed retry count.
                sb.AppendLine();
                sb.Append($"            .RetryTimes({retry.MaxAttempts})");
            }
        }

        if (publishesTrigger)
        {
            // On terminal failure (after any retries), publish the trigger
            // failure-handler command so the saga runs the compensation step (DR-3)
            // and/or the workflow OnFailure chain (#140 Task 3.1).
            // ".Then" is only needed to bridge from a retry continuation back to a
            // failure-action surface; with no retry, OnAnyException() already is one.
            if (retry is not null)
            {
                sb.AppendLine();
                sb.Append("            .Then");
            }

            var triggerCommandName = $"Trigger{model.PascalName}FailureHandlerCommand";

            sb.AppendLine();
            sb.AppendLine($"            .CompensatingAction<{workerCommandName}>(");
            sb.AppendLine($"                (cmd, ex, bus) => bus.PublishAsync(new {triggerCommandName}(");
            sb.AppendLine("                    cmd.WorkflowId,");
            sb.AppendLine($"                    \"{stepName}\",");
            sb.AppendLine("                    ex.Message,");
            sb.AppendLine("                    ex.GetType().Name,");
            sb.AppendLine("                    ex.StackTrace)),");
            sb.Append("                InvokeResult.Stop)");

            if (compensation is not null)
            {
                // Reference the compensation step name in a comment so the lowering is
                // traceable in the generated source.
                var compStepName = NamingHelper.GetSimpleTypeName(compensation.CompensationStepTypeName);
                sb.AppendLine($"; // runs {compStepName}");
            }
            else
            {
                sb.AppendLine("; // routes to OnFailure chain");
            }
        }
        else
        {
            // Retry-only chain: terminate the statement.
            sb.AppendLine(";");
        }

        sb.AppendLine("    }");
    }

    /// <summary>
    /// Builds the comma-separated <see cref="System.TimeSpan"/> argument list for
    /// <c>RetryWithCooldown</c>, one cooldown per retry attempt. The schedule
    /// starts at <paramref name="initialDelay"/> and, when a backoff multiplier
    /// is configured, grows geometrically, capped by <c>MaxDelay</c> if present.
    /// </summary>
    private static string BuildCooldownSchedule(RetryModel retry, System.TimeSpan initialDelay)
    {
        var attempts = retry.MaxAttempts < 1 ? 1 : retry.MaxAttempts;
        var multiplier = retry.BackoffMultiplier ?? 1.0;
        var maxDelay = retry.MaxDelay;

        var parts = new List<string>(attempts);
        var current = initialDelay;
        for (var i = 0; i < attempts; i++)
        {
            var effective = current;
            if (maxDelay is { } cap && effective > cap)
            {
                effective = cap;
            }

            parts.Add(FormatTimeSpan(effective));

            if (multiplier != 1.0)
            {
                current = System.TimeSpan.FromMilliseconds(current.TotalMilliseconds * multiplier);
            }
        }

        return string.Join(", ", parts);
    }

    /// <summary>
    /// Renders a <see cref="System.TimeSpan"/> as a
    /// <c>TimeSpan.FromMilliseconds(...)</c> factory call for the generated
    /// source, preserving sub-second precision used by short retry cooldowns.
    /// </summary>
    private static string FormatTimeSpan(System.TimeSpan value)
    {
        var ms = value.TotalMilliseconds;
        return $"System.TimeSpan.FromMilliseconds({ms.ToString("R", System.Globalization.CultureInfo.InvariantCulture)})";
    }

    private static void EmitHandleMethod(
        StringBuilder sb,
        WorkflowModel model,
        string stepName,
        string workerCommandName,
        string completedEventName,
        string stateType,
        bool hasContext)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Handles the {workerCommandName} by executing the step.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    /// <param name=\"command\">The worker command with workflow state.</param>");
        sb.AppendLine($"    /// <param name=\"ct\">The cancellation token.</param>");
        sb.AppendLine($"    /// <returns>The completion event for saga routing via cascading.</returns>");
        sb.AppendLine("    /// <exception cref=\"ArgumentNullException\">Thrown when <paramref name=\"command\"/> is null.</exception>");
        sb.AppendLine($"    public async Task<{completedEventName}> Handle(");
        sb.AppendLine($"        {workerCommandName} command,");
        sb.AppendLine("        CancellationToken ct)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(command, nameof(command));");
        sb.AppendLine();
        sb.AppendLine($"        _logger.LogDebug(");
        sb.AppendLine($"            \"Executing step {{StepName}} for workflow {{WorkflowId}}\",");
        sb.AppendLine($"            \"{stepName}\",");
        sb.AppendLine("            command.WorkflowId);");
        sb.AppendLine();
        sb.AppendLine($"        using var activity = WorkflowTelemetry.StartStepSpan(\"{stepName}\", command.WorkflowId);");
        sb.AppendLine("        var sw = Stopwatch.StartNew();");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine($"            var stepContext = StepContext.Create(command.WorkflowId, \"{stepName}\", \"{stepName}\");");

        if (hasContext)
        {
            // DR-6 wire-in: assemble the step's declared context (state values,
            // ontology retrieval via IObjectSetProvider, literals) BEFORE the
            // step runs, then deliver it to the step if it opted into the
            // IContextAwareStep side channel. The AssembleAsync call is what
            // actually executes the lowered SimilarityExpression at runtime.
            sb.AppendLine("            var assembledContext = await _contextAssembler.AssembleAsync(command.State, stepContext, ct);");
            sb.AppendLine("            if (_step is IContextAwareStep contextAwareStep)");
            sb.AppendLine("            {");
            sb.AppendLine("                contextAwareStep.ReceiveContext(assembledContext);");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("            var result = await _step.ExecuteAsync(command.State, stepContext, ct);");
        sb.AppendLine();
        sb.AppendLine("            sw.Stop();");
        sb.AppendLine("            activity?.SetStatus(ActivityStatusCode.Ok);");
        sb.AppendLine("            activity?.SetTag(\"step.duration_ms\", sw.ElapsedMilliseconds);");
        sb.AppendLine("            activity?.SetTag(\"step.confidence\", result.Confidence);");
        sb.AppendLine();
        sb.AppendLine($"            _logger.LogDebug(");
        sb.AppendLine($"                \"Step {{StepName}} completed for workflow {{WorkflowId}} in {{ElapsedMs}}ms\",");
        sb.AppendLine($"                \"{stepName}\",");
        sb.AppendLine("                command.WorkflowId,");
        sb.AppendLine("                sw.ElapsedMilliseconds);");
        sb.AppendLine();
        sb.AppendLine("            // Return cascading: Wolverine routes via [SagaIdentity] on the event");
        sb.AppendLine($"            return new {completedEventName}(");
        sb.AppendLine("                command.WorkflowId,");
        sb.AppendLine("                command.StepExecutionId,");
        sb.AppendLine("                result.UpdatedState,");
        sb.AppendLine("                result.Confidence,");
        sb.AppendLine("                DateTimeOffset.UtcNow);");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            sw.Stop();");
        sb.AppendLine("            activity?.SetStatus(ActivityStatusCode.Error, ex.Message);");
        sb.AppendLine("            activity?.SetTag(\"step.duration_ms\", sw.ElapsedMilliseconds);");
        sb.AppendLine("            activity?.SetTag(\"error.type\", ex.GetType().Name);");
        sb.AppendLine();
        sb.AppendLine($"            _logger.LogError(");
        sb.AppendLine("                ex,");
        sb.AppendLine($"                \"Step {{StepName}} failed for workflow {{WorkflowId}} after {{ElapsedMs}}ms: {{ErrorMessage}}\",");
        sb.AppendLine($"                \"{stepName}\",");
        sb.AppendLine("                command.WorkflowId,");
        sb.AppendLine("                sw.ElapsedMilliseconds,");
        sb.AppendLine("                ex.Message);");
        sb.AppendLine();
        sb.AppendLine("            // Re-throw to let Wolverine handle retry/dead-letter");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }
}
