#!/usr/bin/env bash
# -----------------------------------------------------------------------
# pack-to-local-feed.sh
#
# DR-11 / T-022 — release-readiness packaging step.
#
# Packs src/Strategos.Agents/Strategos.Agents.csproj into a local
# directory-based NuGet feed, so that the smoke project at
# tests/basileus-smoke/Basileus.Smoke.Tests can restore the
# LevelUp.Strategos.Agents package at its pinned 2.7.0-preview.2
# version.
#
# Usage:
#   scripts/pack-to-local-feed.sh [feed-dir]
#
# Default feed-dir: ./local-feed (relative to the repo root, which is
# expected to be the script invoker's cwd — mirroring how
# scripts/verify-generator-consumer-build.sh is invoked from CI).
#
# Idempotent:
#   * Re-running overwrites the .nupkg in feed-dir (dotnet pack handles
#     this without prompting).
#   * The smoke project consumes the feed via its own local
#     tests/basileus-smoke/Basileus.Smoke.Tests/nuget.config — this
#     script intentionally does NOT mutate the user's global
#     NuGet.Config. (Earlier drafts used `dotnet nuget add source`; we
#     dropped it because it leaves persistent state on the host and
#     because the smoke project's nuget.config makes it unnecessary.)
#
# Exit codes:
#   0  pack succeeded and the expected nupkg is present
#   1  invalid arguments / setup error
#   2  pack failed (regression in Strategos.Agents.csproj)
#   3  pack succeeded but produced an unexpected version
#
# Versioning note: Strategos.Agents.csproj is MinVer-derived (no explicit
# <Version> pin) so it ships 2.7.0 at the release tag and 0.0.0-alpha.0 on
# tagless CI, uniform with every sibling. The smoke gate does not care about the
# real shipping version — it validates the basileus-consumed surface against a
# packed artifact — so we pack at a deterministic SYNTHETIC prerelease version
# here (overriding MinVer for this pack only). It is prerelease, so it may depend
# on the prerelease core MinVer produces on tagless CI without tripping NU5104;
# and nuget.org will never carry it, so the smoke project's PackageReference
# resolves it unambiguously from the local feed.
# -----------------------------------------------------------------------
set -euo pipefail

FEED_DIR="${1:-./local-feed}"
SMOKE_VERSION="2.7.0-smoke"
EXPECTED_NUPKG_NAME="LevelUp.Strategos.Agents.${SMOKE_VERSION}.nupkg"

# Resolve to absolute path so downstream messages are unambiguous, even
# if the script is invoked from a deeper cwd.
mkdir -p "$FEED_DIR"
FEED_DIR_ABS="$(cd "$FEED_DIR" && pwd)"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
AGENTS_CSPROJ="$REPO_ROOT/src/Strategos.Agents/Strategos.Agents.csproj"

if [[ ! -f "$AGENTS_CSPROJ" ]]; then
  echo "ERROR: Strategos.Agents.csproj not found at $AGENTS_CSPROJ" >&2
  exit 1
fi

echo "Pack: $AGENTS_CSPROJ"
echo "Feed: $FEED_DIR_ABS"
echo "Expecting: $EXPECTED_NUPKG_NAME"

# Remove any prior copies of the package from the feed dir so a stale
# build does not mask a regression. We scope the rm to this package
# name only — co-resident packages (e.g. snupkg symbols) are left in
# place but will be regenerated by `dotnet pack` below.
rm -f "$FEED_DIR_ABS"/LevelUp.Strategos.Agents.*.nupkg \
      "$FEED_DIR_ABS"/LevelUp.Strategos.Agents.*.snupkg

# Pack at the synthetic prerelease SMOKE_VERSION. AgentsSmokeVersion is consumed
# only by Strategos.Agents.csproj (a guarded PropertyGroup), so the override does
# NOT propagate to the core LevelUp.Strategos ProjectReference — core stays
# MinVer-derived and the stamped dependency floats low (prerelease on tagless CI),
# which is why a prerelease SMOKE_VERSION avoids NU5104.
if ! dotnet pack "$AGENTS_CSPROJ" \
       -c Release \
       -o "$FEED_DIR_ABS" \
       --nologo \
       -p:AgentsSmokeVersion="$SMOKE_VERSION" \
       -v:m; then
  echo "FAIL: dotnet pack of $AGENTS_CSPROJ failed." >&2
  exit 2
fi

if [[ ! -f "$FEED_DIR_ABS/$EXPECTED_NUPKG_NAME" ]]; then
  echo "FAIL: expected nupkg $EXPECTED_NUPKG_NAME not produced in $FEED_DIR_ABS." >&2
  echo "Produced packages:" >&2
  ls -1 "$FEED_DIR_ABS" >&2 || true
  echo "Hint: SMOKE_VERSION ($SMOKE_VERSION) must match the smoke project's PackageReference." >&2
  exit 3
fi

echo "OK: $FEED_DIR_ABS/$EXPECTED_NUPKG_NAME ready for smoke-project restore."
