// -----------------------------------------------------------------------
// <copyright file="SagaEmitterUnitTests.cs" company="Levelup Software">
// Copyright (c) Levelup Software. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using Strategos.Generators.Emitters;
using Strategos.Generators.Models;

namespace Strategos.Generators.Tests.Emitters;

/// <summary>
/// Unit tests for the <see cref="SagaEmitter"/> class.
/// </summary>
[Property("Category", "Unit")]
public class SagaEmitterUnitTests
{
    // =============================================================================
    // A. Emit Guard Tests
    // =============================================================================

    /// <summary>
    /// Verifies that Emit throws for null model.
    /// </summary>
    [Test]
    public async Task Emit_NullModel_ThrowsArgumentNullException()
    {
        // Act & Assert
        await Assert.That(() => SagaEmitter.Emit(null!))
            .Throws<ArgumentNullException>();
    }

    /// <summary>
    /// Verifies that Emit exception includes parameter name.
    /// </summary>
    [Test]
    public async Task Emit_NullModel_ExceptionIncludesParameterName()
    {
        // Act
        ArgumentNullException? exception = null;
        try
        {
            SagaEmitter.Emit(null!);
        }
        catch (ArgumentNullException ex)
        {
            exception = ex;
        }

        // Assert
        await Assert.That(exception).IsNotNull();
        await Assert.That(exception!.ParamName).IsEqualTo("model");
    }

    // =============================================================================
    // B. GetSagaClassName Guard Tests
    // =============================================================================

    /// <summary>
    /// Verifies that GetSagaClassName throws for null model.
    /// </summary>
    [Test]
    public async Task GetSagaClassName_NullModel_ThrowsArgumentNullException()
    {
        // Act & Assert
        await Assert.That(() => SagaEmitter.GetSagaClassName(null!))
            .Throws<ArgumentNullException>();
    }

    /// <summary>
    /// Verifies that GetSagaClassName exception includes parameter name.
    /// </summary>
    [Test]
    public async Task GetSagaClassName_NullModel_ExceptionIncludesParameterName()
    {
        // Act
        ArgumentNullException? exception = null;
        try
        {
            SagaEmitter.GetSagaClassName(null!);
        }
        catch (ArgumentNullException ex)
        {
            exception = ex;
        }

        // Assert
        await Assert.That(exception).IsNotNull();
        await Assert.That(exception!.ParamName).IsEqualTo("model");
    }

    // =============================================================================
    // C. GetSagaClassName Behavior Tests
    // =============================================================================

    /// <summary>
    /// Verifies that GetSagaClassName returns correct name for version 1.
    /// </summary>
    [Test]
    public async Task GetSagaClassName_Version1_ReturnsNameWithoutSuffix()
    {
        // Arrange
        var model = CreateMinimalModel(version: 1);

        // Act
        var result = SagaEmitter.GetSagaClassName(model);

        // Assert
        await Assert.That(result).IsEqualTo("TestWorkflowSaga");
    }

    /// <summary>
    /// Verifies that GetSagaClassName returns correct name for version 2.
    /// </summary>
    [Test]
    public async Task GetSagaClassName_Version2_ReturnsNameWithV2Suffix()
    {
        // Arrange
        var model = CreateMinimalModel(version: 2);

        // Act
        var result = SagaEmitter.GetSagaClassName(model);

        // Assert
        await Assert.That(result).IsEqualTo("TestWorkflowSagaV2");
    }

    /// <summary>
    /// Verifies that GetSagaClassName returns correct name for higher versions.
    /// </summary>
    [Test]
    public async Task GetSagaClassName_Version5_ReturnsNameWithV5Suffix()
    {
        // Arrange
        var model = CreateMinimalModel(version: 5);

        // Act
        var result = SagaEmitter.GetSagaClassName(model);

        // Assert
        await Assert.That(result).IsEqualTo("TestWorkflowSagaV5");
    }

    // =============================================================================
    // D. Emit Output Structure Tests
    // =============================================================================

    /// <summary>
    /// Verifies that Emit produces auto-generated header.
    /// </summary>
    [Test]
    public async Task Emit_ValidModel_ProducesAutoGeneratedHeader()
    {
        // Arrange
        var model = CreateMinimalModel();

        // Act
        var result = SagaEmitter.Emit(model);

        // Assert
        await Assert.That(result).Contains("// <auto-generated/>");
    }

    /// <summary>
    /// Verifies that Emit enables nullable reference types.
    /// </summary>
    [Test]
    public async Task Emit_ValidModel_EnablesNullable()
    {
        // Arrange
        var model = CreateMinimalModel();

        // Act
        var result = SagaEmitter.Emit(model);

        // Assert
        await Assert.That(result).Contains("#nullable enable");
    }

    /// <summary>
    /// Verifies that Emit includes correct namespace.
    /// </summary>
    [Test]
    public async Task Emit_ValidModel_IncludesNamespace()
    {
        // Arrange
        var model = CreateMinimalModel();

        // Act
        var result = SagaEmitter.Emit(model);

        // Assert
        await Assert.That(result).Contains("namespace TestNamespace;");
    }

    /// <summary>
    /// Verifies that Emit includes required usings.
    /// </summary>
    [Test]
    public async Task Emit_ValidModel_IncludesRequiredUsings()
    {
        // Arrange
        var model = CreateMinimalModel();

        // Act
        var result = SagaEmitter.Emit(model);

        // Assert
        await Assert.That(result).Contains("using System;");
        await Assert.That(result).Contains("using Wolverine.Persistence.Sagas;");
    }

    /// <summary>
    /// Verifies that Emit produces class extending Saga.
    /// </summary>
    [Test]
    public async Task Emit_ValidModel_ExtendsSaga()
    {
        // Arrange
        var model = CreateMinimalModel();

        // Act
        var result = SagaEmitter.Emit(model);

        // Assert
        await Assert.That(result).Contains(": Saga");
    }

    // =============================================================================
    // E. Emit with Empty StepNames Tests
    // =============================================================================

    /// <summary>
    /// Verifies that Emit handles empty StepNames gracefully.
    /// </summary>
    [Test]
    public async Task Emit_EmptyStepNames_ProducesValidOutput()
    {
        // Arrange
        var model = new WorkflowModel(
            WorkflowName: "test-workflow",
            PascalName: "TestWorkflow",
            Namespace: "TestNamespace",
            StepNames: []);

        // Act
        var result = SagaEmitter.Emit(model);

        // Assert - Should produce valid output with fallback "Unknown" step
        await Assert.That(result).Contains("// <auto-generated/>");
        await Assert.That(result).Contains(": Saga");
    }

    // =============================================================================
    // Helper Methods
    // =============================================================================

    private static WorkflowModel CreateMinimalModel(int version = 1)
    {
        return new WorkflowModel(
            WorkflowName: "test-workflow",
            PascalName: "TestWorkflow",
            Namespace: "TestNamespace",
            StepNames: ["ValidateStep", "ProcessStep"],
            StateTypeName: "TestState",
            Version: version);
    }
}
